import importlib.util
import re
import subprocess
from pathlib import Path

import pytest


pytestmark = pytest.mark.no_infrastructure

ROOT = Path(__file__).resolve().parents[1]
PG_PROD = ROOT / "db-prod-pg"


def load_apply_sql_module():
    path = PG_PROD / "apply_sql.py"
    if not path.exists():
        pytest.fail(f"missing PostgreSQL importer: {path}")
    spec = importlib.util.spec_from_file_location("pg_prod_apply_sql", path)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_pg_importer_requires_explicit_target_database():
    module = load_apply_sql_module()

    with pytest.raises(SystemExit):
        module.parse_args([str(PG_PROD / "V0-baseline.sql")])


def test_pg_importer_defaults_to_postgresql_port():
    module = load_apply_sql_module()

    args = module.parse_args(
        [
            str(PG_PROD / "V0-baseline.sql"),
            "--host",
            "127.0.0.1",
            "--user",
            "postgres",
            "--password",
            "secret",
            "--database",
            "nanzi_ai_agent_platform",
        ]
    )

    assert args.port == 5432
    assert module.build_config(args).database == "nanzi_ai_agent_platform"


@pytest.mark.parametrize("database", ["postgres", "template0", "template1", "", "bad-name!"])
def test_pg_importer_rejects_protected_or_invalid_target_database(database):
    module = load_apply_sql_module()

    with pytest.raises(ValueError):
        module.validate_target_database(database)


def test_pg_importer_splits_dollar_quoted_and_string_semicolons():
    module = load_apply_sql_module()

    statements = module.split_sql_statements(
        """
        CREATE TABLE demo (id integer);
        INSERT INTO demo VALUES (1, 'value;still-one-statement');
        DO $$
        BEGIN
            PERFORM 1;
        END
        $$;
        """
    )

    assert len(statements) == 3
    assert "value;still-one-statement" in statements[1]
    assert statements[2].startswith("DO $$")


def test_pg_baseline_contains_current_schema_without_mysql_only_tokens():
    baseline = (PG_PROD / "V0-baseline.sql").read_text(encoding="utf-8")
    upper = baseline.upper()

    for table_name in (
        "ai_agent_users",
        "ai_agents",
        "ai_agent_versions",
        "system_configs",
        "meta_datasets",
        "ai_agent_execution_traces",
        "ai_agent_scheduler_jobs",
        "portal_saved_reports",
        "db_table_profiles",
    ):
        assert f'CREATE TABLE IF NOT EXISTS "{table_name}"' in baseline

    assert "GENERATED BY DEFAULT AS IDENTITY" in upper
    assert "JSONB" in upper
    assert "BYTEA" in upper

    for mysql_only in (
        "AUTO_INCREMENT",
        "ENGINE=INNODB",
        "ON DUPLICATE KEY",
        "INSERT IGNORE",
        "`",
    ):
        assert mysql_only not in upper


def test_pg_baseline_has_chinese_comments_for_every_baseline_column():
    baseline = (PG_PROD / "V0-baseline.sql").read_text(encoding="utf-8")

    column_definitions = re.findall(r'^\s+"[^"]+"\s+', baseline, flags=re.MULTILINE)
    column_comments = re.findall(r'^COMMENT ON COLUMN ', baseline, flags=re.MULTILINE)

    assert baseline.count("CREATE TABLE IF NOT EXISTS") == 44
    assert baseline.count("COMMENT ON TABLE") == 44
    assert len(column_comments) == len(column_definitions)
    assert re.search(r"[一-鿿]", baseline)


def test_pg_baseline_places_field_remarks_inside_create_tables():
    baseline = (PG_PROD / "V0-baseline.sql").read_text(encoding="utf-8")
    table_blocks = re.findall(
        r'CREATE TABLE IF NOT EXISTS "([^"]+)" \((.*?)\n\);',
        baseline,
        flags=re.DOTALL,
    )

    for table_name, body in table_blocks:
        lines = body.splitlines()
        for index, line in enumerate(lines):
            if re.match(r'^\s+"[^"]+"\s+', line):
                assert lines[index - 1].strip().startswith("--"), table_name


def test_pg_wrapper_exists_and_calls_python_importer():
    wrapper = (PG_PROD / "apply-sql.sh").read_text(encoding="utf-8")

    assert "apply_sql.py" in wrapper
    assert "python3" in wrapper


def test_pg_wrapper_reexecutes_with_bash_when_invoked_via_sh():
    wrapper = (PG_PROD / "apply-sql.sh").read_text(encoding="utf-8")

    assert 'if [ -z "$BASH_VERSION" ]' in wrapper
    assert 'exec bash "$0" "$@"' in wrapper


def test_pg_wrapper_can_start_via_sh_without_shell_syntax_error():
    result = subprocess.run(
        ["sh", str(PG_PROD / "apply-sql.sh")],
        input="\n\n\n\n\n",
        text=True,
        capture_output=True,
        check=False,
    )

    output = result.stdout + result.stderr
    assert result.returncode == 1
    assert "Host、User、Target database 都必须手动输入" in output
    assert "syntax error" not in output


def test_pg_config_alignment_migration_contains_mysql_final_config_keys():
    migration = (PG_PROD / "V1-align_system_config_seeds.sql").read_text(encoding="utf-8")

    expected_keys = (
        "ragflow_similarity_threshold",
        "ragflow_vector_weight",
        "external_sql_data_source",
        "agent_max_context_messages",
        "chatbi_sample_similarity_threshold",
        "chatbi_sample_vector_similarity_weight",
        "ragflow_metadata_top_k",
        "sql_execution_mode",
        "embedchat_watermark_enabled",
        "embedchat_watermark_style",
        "embedchat_watermark_text",
        "yovole_sso_enabled",
        "embed_api_url",
        "embed_api_key",
        "embed_model_name",
        "embed_dimensions",
        "chatbi_sample_top_k",
        "knowledge_ragflow_api_url",
        "knowledge_ragflow_api_key",
        "knowledge_ragflow_dataset_ids",
        "knowledge_ragflow_metadata_top_k",
        "knowledge_ragflow_similarity_threshold",
        "knowledge_ragflow_vector_weight",
        "branding.enabled",
        "branding.product_name",
        "branding.login_subtitle",
        "branding.icon_url",
        "branding.hide_login_sso",
        "branding.hide_version_link",
        "branding.contact_markdown",
        "branding.copyright_text",
        "third_party_user_sync_config",
        "knowledge_base_enabled",
        "llm_model_name",
        "llm_temperature",
        "chatbi_sample_knowledge_base",
    )

    for key in expected_keys:
        assert f"'{key}'" in migration

    assert 'ON CONFLICT ("key") DO UPDATE' in migration
    assert '"value" = EXCLUDED."value"' not in migration
    assert "'llm_model_name', 'DeepSeek-V3.2', '系统默认模型', 'agent', FALSE" in migration
    assert "'llm_temperature', '0.0', 'LLM 温度参数', 'agent', FALSE" in migration
    assert "'chatbi_sample_knowledge_base', '', '用于存放用户点赞沉淀的优质 SQL 案例的 RAGFlow 数据集 ID', 'data_api', FALSE" in migration
    assert "'sql_execution_mode', 'local', 'SQL 执行模式" in migration


def test_pg_config_alignment_migration_uses_postgresql_not_mysql_upsert_syntax():
    migration = (PG_PROD / "V1-align_system_config_seeds.sql").read_text(encoding="utf-8").upper()

    assert "ON DUPLICATE KEY" not in migration
    assert "INSERT IGNORE" not in migration
