-- NanZi AI Agent Platform PostgreSQL baseline
--
-- This is a current-state baseline for a new PostgreSQL platform database.
-- It intentionally does not replay the historical MySQL migration chain.
-- JSON values use JSONB, generated keys use PostgreSQL identity columns, and
-- APScheduler's binary payload uses BYTEA.
-- PostgreSQL does not support MySQL-style inline COMMENT clauses in column
-- definitions. The -- comments inside each CREATE TABLE are the readable
-- inline remarks; COMMENT ON statements below also persist them in pg_catalog.

CREATE TABLE IF NOT EXISTS "ai_agent_users" (
    -- 表说明：智能体平台用户表
    -- 用户主键 ID
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 登录用户名
    "user_name" VARCHAR(64) NOT NULL UNIQUE,
    -- 用户真实姓名
    "real_name" VARCHAR(50),
    -- 加密存储的 API Key
    "api_key_encrypted" TEXT,
    -- API Key 的 SHA256 哈希值
    "api_key_hash" VARCHAR(64) UNIQUE,
    -- 用户密码哈希值
    "password_hash" VARCHAR(255),
    -- 平台角色：admin 或 user
    "role" VARCHAR(32) NOT NULL DEFAULT 'user',
    -- 部门唯一标识 ID
    "dept_id" INTEGER,
    -- 部门代码
    "dept_code" VARCHAR(50),
    -- 组织结构全路径
    "org_path" VARCHAR(255),
    -- 用户扩展数据，保存 JSON 文本
    "extra_data" TEXT,
    -- 用户备注
    "remark" VARCHAR(500),
    -- 用户状态：1 启用，0 停用
    "status" SMALLINT NOT NULL DEFAULT 1,
    -- 创建时间
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- 最后更新时间
    "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "system_configs" (
    -- 表说明：系统动态配置表
    -- 配置键名
    "key" VARCHAR(255) PRIMARY KEY,
    -- 配置值
    "value" TEXT,
    -- 配置说明
    "description" VARCHAR(255),
    -- 配置分类
    "category" VARCHAR(50) NOT NULL DEFAULT 'general',
    -- 是否为敏感配置
    "is_secret" BOOLEAN NOT NULL DEFAULT FALSE,
    -- 创建时间
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- 最后更新时间
    "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "system_config_history" (
    -- 表说明：系统配置变更历史审计表
    -- 变更记录主键 ID
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 被变更的配置键名
    "config_key" VARCHAR(255) NOT NULL,
    -- 变更前的配置值
    "old_value" TEXT,
    -- 变更后的配置值
    "new_value" TEXT,
    -- 变更描述或备注
    "description" TEXT,
    -- 变更操作人
    "changed_by" VARCHAR(64) NOT NULL DEFAULT 'system',
    -- 变更类型：UPDATE、CREATE 或 DELETE
    "change_type" VARCHAR(20) NOT NULL DEFAULT 'UPDATE',
    -- 变更时间
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "slash_commands" (
    -- 表说明：调试快捷指令表
    -- 快捷指令主键 ID
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 前端显示名称
    "label" VARCHAR(50) NOT NULL,
    -- 执行指令内容
    "command" TEXT NOT NULL,
    -- 排序权重
    "sort_order" INTEGER NOT NULL DEFAULT 0,
    -- 创建人
    "created_by" VARCHAR(64) NOT NULL DEFAULT 'system',
    -- 创建时间
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- 最后更新时间
    "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "memory_service_configs" (
    -- 表说明：记忆管理中心服务配置表
    -- 记忆服务配置键名
    "key" VARCHAR(255) PRIMARY KEY,
    -- 记忆服务配置值
    "value" TEXT,
    -- 配置说明
    "description" VARCHAR(255),
    -- 是否为敏感配置
    "is_secret" BOOLEAN NOT NULL DEFAULT FALSE,
    -- 创建时间
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- 最后更新时间
    "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "ai_agents" (
    -- 表说明：智能体定义表
    -- 智能体唯一 ID
    "id" VARCHAR(36) PRIMARY KEY,
    -- 智能体内部名称
    "name" VARCHAR(100) NOT NULL UNIQUE,
    -- 智能体显示名称
    "display_name" VARCHAR(100) NOT NULL,
    -- 智能体功能描述
    "description" TEXT,
    -- 智能体头像地址
    "avatar_url" VARCHAR(255),
    -- 智能体能力标签 JSON
    "capabilities" JSONB,
    -- 面向用户的智能体类型
    "agent_type" VARCHAR(32) NOT NULL DEFAULT 'GENERAL',
    -- 新手引导标识
    "onboarding_key" VARCHAR(64),
    -- 当前新手引导步骤
    "onboarding_step" VARCHAR(20) NOT NULL DEFAULT 'COMPLETE',
    -- 是否为系统内置智能体
    "is_system" BOOLEAN NOT NULL DEFAULT FALSE,
    -- 智能体排序值
    "sort_order" INTEGER NOT NULL DEFAULT 0,
    -- 是否启用
    "is_enabled" BOOLEAN NOT NULL DEFAULT TRUE,
    -- 运行引擎类型
    "engine_type" VARCHAR(20) NOT NULL DEFAULT 'LOCAL',
    -- 运行引擎配置 JSON
    "engine_config" JSONB,
    -- 创建者用户名
    "created_by" VARCHAR(64) DEFAULT 'admin',
    -- 所属用户组
    "owner_group" VARCHAR(50),
    -- 创建时间
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- 最后更新时间
    "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "uk_ai_agents_owner_onboarding" UNIQUE ("created_by", "onboarding_key")
);

CREATE TABLE IF NOT EXISTS "ai_agent_versions" (
    -- 表说明：智能体版本与提示词配置表
    -- 版本唯一 ID
    "id" VARCHAR(36) PRIMARY KEY,
    -- 所属智能体 ID
    "agent_id" VARCHAR(36) NOT NULL,
    -- 版本序号
    "version_number" INTEGER NOT NULL,
    -- 主模型名称
    "model_name" VARCHAR(100),
    -- 主模型温度参数
    "temperature" REAL NOT NULL DEFAULT 0.0,
    -- 合成模型名称
    "synthesis_model_name" VARCHAR(100),
    -- 合成模型温度参数
    "synthesis_temperature" REAL,
    -- 系统提示词
    "system_prompt" TEXT NOT NULL,
    -- 允许使用的工具列表 JSON
    "tools" JSONB,
    -- 是否自定义公共 Skills
    "skills_custom" BOOLEAN NOT NULL DEFAULT FALSE,
    -- 自定义公共技能 ID 列表 JSON
    "skills" JSONB,
    -- 欢迎页三卡片配置 JSON
    "welcome_config" JSONB,
    -- 版本状态：DRAFT、PUBLISHED 或 ARCHIVED
    "status" VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    -- 版本变更说明
    "comment" TEXT,
    -- 创建时间
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "fk_ai_agent_versions_agent"
        FOREIGN KEY ("agent_id") REFERENCES "ai_agents" ("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "ai_models" (
    -- 表说明：平台模型配置表
    -- 模型配置唯一 ID
    "id" VARCHAR(36) PRIMARY KEY,
    -- 模型显示名称
    "name" VARCHAR(255) NOT NULL,
    -- 供应商侧模型标识
    "model_id" VARCHAR(255) NOT NULL,
    -- 模型供应商
    "provider" VARCHAR(50) NOT NULL,
    -- 模型类型：llm 或 embedding
    "type" VARCHAR(50) NOT NULL,
    -- 模型 API 地址覆盖值
    "api_base_url" VARCHAR(512),
    -- 模型 API Key
    "api_key" VARCHAR(512),
    -- 是否启用
    "is_active" BOOLEAN NOT NULL DEFAULT TRUE,
    -- 创建时间
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- 最后更新时间
    "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "ai_agent_roles" (
    -- 表说明：智能体平台角色表
    -- 角色主键 ID
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 角色编码
    "code" VARCHAR(50) NOT NULL UNIQUE,
    -- 角色名称
    "name" VARCHAR(50) NOT NULL,
    -- 角色说明
    "description" VARCHAR(255),
    -- 创建时间
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- 最后更新时间
    "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "ai_agent_user_role_relations" (
    -- 表说明：用户与角色关系表
    -- 关系记录主键 ID
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 用户 ID
    "user_id" BIGINT NOT NULL,
    -- 角色 ID
    "role_id" BIGINT NOT NULL,
    -- 关系创建时间
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "uk_user_role" UNIQUE ("user_id", "role_id"),
    CONSTRAINT "fk_user_role_user"
        FOREIGN KEY ("user_id") REFERENCES "ai_agent_users" ("id") ON DELETE CASCADE,
    CONSTRAINT "fk_user_role_role"
        FOREIGN KEY ("role_id") REFERENCES "ai_agent_roles" ("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "ai_agent_resource_permissions" (
    -- 表说明：智能体资源权限表
    -- 权限记录主键 ID
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 授权用户 ID
    "user_id" BIGINT,
    -- 授权角色 ID
    "role_id" BIGINT,
    -- 资源类型：agent、dataset、menu 或 element
    "resource_type" VARCHAR(20) NOT NULL,
    -- 资源业务 ID
    "resource_id" VARCHAR(100) NOT NULL,
    -- 是否启用该权限
    "enabled" BOOLEAN NOT NULL DEFAULT TRUE,
    -- 创建时间
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- 最后更新时间
    "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "meta_datasets" (
    -- 表说明：业务数据集定义表
    -- 数据集主键 ID
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 数据集内部名称
    "name" VARCHAR(100) NOT NULL UNIQUE,
    -- 数据集显示名称
    "display_name" VARCHAR(100),
    -- 数据集业务描述
    "description" TEXT,
    -- 数据集标签 JSON
    "tags" JSONB,
    -- 数据源类型：clickhouse、mysql、postgresql 等
    "data_source" VARCHAR(50) NOT NULL DEFAULT 'clickhouse',
    -- 数据集状态：1 启用，0 停用
    "status" SMALLINT NOT NULL DEFAULT 0,
    -- 是否启用精细化数据权限
    "enable_data_perm" BOOLEAN NOT NULL DEFAULT FALSE,
    -- 行级权限过滤策略 JSON
    "row_filter_config" JSONB,
    -- RAGFlow Dataset ID
    "rag_dataset_id" VARCHAR(64),
    -- 最后同步到 RAGFlow 的时间
    "rag_synced_at" TIMESTAMP,
    -- RAGFlow 同步状态
    "rag_sync_status" SMALLINT NOT NULL DEFAULT 0,
    -- RAGFlow 同步日志或错误信息
    "rag_sync_notes" TEXT,
    -- 创建时间
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- 最后更新时间
    "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "meta_tables" (
    -- 表说明：数据集物理表元数据定义表
    -- 物理表元数据主键 ID
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 所属数据集 ID
    "dataset_id" INTEGER NOT NULL,
    -- 物理表名
    "physical_name" VARCHAR(255) NOT NULL,
    -- 表的业务术语
    "term" VARCHAR(255) NOT NULL,
    -- 表的业务描述
    "description" TEXT,
    -- 表的同义词列表 JSON
    "synonyms" JSONB,
    -- 表状态：1 启用，0 停用
    "status" SMALLINT NOT NULL DEFAULT 1,
    -- 创建时间
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- 最后更新时间
    "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "uix_dataset_physical_name" UNIQUE ("dataset_id", "physical_name"),
    CONSTRAINT "fk_meta_tables_dataset"
        FOREIGN KEY ("dataset_id") REFERENCES "meta_datasets" ("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "meta_columns" (
    -- 表说明：物理表字段元数据定义表
    -- 字段元数据主键 ID
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 所属物理表 ID
    "table_id" INTEGER NOT NULL,
    -- 物理字段名
    "physical_name" VARCHAR(255) NOT NULL,
    -- 字段业务术语
    "term" VARCHAR(255) NOT NULL,
    -- 字段业务或数据库类型
    "type" VARCHAR(50),
    -- 字段业务描述
    "description" TEXT,
    -- 枚举值定义 JSON
    "enums" JSONB,
    -- 字段同义词列表 JSON
    "synonyms" JSONB,
    -- 字段示例值列表 JSON
    "examples" JSONB,
    -- 外键关联描述
    "foreign_key" VARCHAR(255),
    -- 是否为业务主键字段
    "is_primary" SMALLINT NOT NULL DEFAULT 0,
    -- 创建时间
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "uk_table_col" UNIQUE ("table_id", "physical_name"),
    CONSTRAINT "fk_meta_columns_table"
        FOREIGN KEY ("table_id") REFERENCES "meta_tables" ("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "meta_metrics" (
    -- 表说明：业务指标定义表
    -- 指标主键 ID
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 所属数据集 ID
    "dataset_id" INTEGER NOT NULL,
    -- 指标内部名称
    "name" VARCHAR(100) NOT NULL,
    -- 指标显示名称
    "display_name" VARCHAR(100) NOT NULL,
    -- 业务口径描述
    "description" TEXT,
    -- 指标计算逻辑或公式
    "calculation_logic" TEXT,
    -- 指标单位
    "unit" VARCHAR(20),
    -- 创建时间
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- 最后更新时间
    "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "uk_dataset_name" UNIQUE ("dataset_id", "name"),
    CONSTRAINT "fk_meta_metrics_dataset"
        FOREIGN KEY ("dataset_id") REFERENCES "meta_datasets" ("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "meta_relationships" (
    -- 表说明：元数据表间关系定义表
    -- 关系主键 ID
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 源表 ID
    "source_table_id" INTEGER NOT NULL,
    -- 目标表 ID
    "target_table_id" INTEGER NOT NULL,
    -- 表关联条件
    "join_condition" VARCHAR(255) NOT NULL,
    -- 关联类型：LEFT、INNER 或 RIGHT
    "join_type" VARCHAR(20) NOT NULL DEFAULT 'LEFT',
    -- 关系业务描述
    "description" TEXT,
    CONSTRAINT "fk_rel_source"
        FOREIGN KEY ("source_table_id") REFERENCES "meta_tables" ("id") ON DELETE CASCADE,
    CONSTRAINT "fk_rel_target"
        FOREIGN KEY ("target_table_id") REFERENCES "meta_tables" ("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "meta_changelog" (
    -- 表说明：元数据变更日志表
    -- 变更日志主键 ID
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 资源类型：dataset、table、column、metric 或 relationship
    "resource_type" VARCHAR(20) NOT NULL,
    -- 资源业务 ID
    "resource_id" VARCHAR(270) NOT NULL,
    -- 操作类型：create、update 或 delete
    "operation" VARCHAR(20) NOT NULL,
    -- 变更前数据 JSON
    "old_data" JSONB,
    -- 变更后数据 JSON
    "new_data" JSONB,
    -- 变更字段列表 JSON
    "changed_fields" JSONB,
    -- 操作用户 ID
    "user_id" INTEGER,
    -- 操作用户名
    "user_name" VARCHAR(64),
    -- 变更原因
    "reason" TEXT,
    -- 变更时间
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "meta_db_connection_configs" (
    -- 表说明：外部数据源连接配置表
    -- 连接配置主键 ID
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 连接别名
    "name" VARCHAR(100) NOT NULL,
    -- 外部数据库类型
    "db_type" VARCHAR(20) NOT NULL,
    -- 外部数据库主机地址
    "host" VARCHAR(255) NOT NULL,
    -- 外部数据库端口
    "port" INTEGER NOT NULL,
    -- 外部数据库用户名
    "db_user" VARCHAR(100) NOT NULL,
    -- 外部数据库密码
    "password" VARCHAR(255) NOT NULL DEFAULT '',
    -- 外部数据库名称
    "database_name" VARCHAR(100) NOT NULL,
    -- 数据源用途说明
    "description" VARCHAR(500) NOT NULL DEFAULT '',
    -- 创建用户 ID
    "created_by" INTEGER NOT NULL DEFAULT 0,
    -- 创建时间
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- 最后更新时间
    "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "uk_meta_db_connection_configs_name" UNIQUE ("name")
);

CREATE TABLE IF NOT EXISTS "db_profile_tasks" (
    -- 表说明：外部数据源摸排任务表
    -- 摸排任务主键 ID
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 外部数据源连接配置 ID
    "connection_id" INTEGER NOT NULL,
    -- 任务状态：0 排队，1 进行中，2 完成，3 异常
    "status" SMALLINT NOT NULL DEFAULT 0,
    -- 待处理表或视图总数
    "total_tables" INTEGER NOT NULL DEFAULT 0,
    -- 已处理表或视图数量
    "processed_tables" INTEGER NOT NULL DEFAULT 0,
    -- 当前正在处理的物理表名
    "current_table" VARCHAR(100),
    -- 任务异常说明
    "error_message" TEXT,
    -- 创建时间
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- 最后更新时间
    "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "uk_conn_task" UNIQUE ("connection_id"),
    CONSTRAINT "fk_task_conn"
        FOREIGN KEY ("connection_id") REFERENCES "meta_db_connection_configs" ("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "db_table_profiles" (
    -- 表说明：外部数据源表与视图画像草稿表
    -- 表画像主键 ID
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 外部数据源连接配置 ID
    "connection_id" INTEGER NOT NULL,
    -- 数据库物理表或视图名
    "table_name" VARCHAR(100) NOT NULL,
    -- 对象类型：table 或 view
    "table_type" VARCHAR(20) NOT NULL,
    -- 外部对象存储引擎
    "engine" VARCHAR(50),
    -- 物理建表 DDL
    "ddl" TEXT,
    -- 采样数据 JSON 文本
    "sample_data" TEXT,
    -- AI 识别的业务术语
    "ai_term" VARCHAR(100),
    -- AI 生成的业务用途描述
    "ai_description" VARCHAR(500),
    -- AI 生成的分类标签 JSON
    "ai_tags" JSONB,
    -- AI 生成的字段画像 JSON
    "columns_profile" JSONB,
    -- 摸排状态：0 待开始，1 进行中，2 成功，3 失败
    "status" SMALLINT NOT NULL DEFAULT 0,
    -- 业务相关度置信度评分，范围 0 到 100
    "confidence_score" SMALLINT NOT NULL DEFAULT 100,
    -- 是否为临时或备份表
    "is_temporary" SMALLINT NOT NULL DEFAULT 0,
    -- 分析时是否忽略该表
    "is_ignored" SMALLINT NOT NULL DEFAULT 0,
    -- 置信度判定与扣分原因
    "confidence_reason" TEXT,
    -- 画像分析失败说明
    "error_message" TEXT,
    -- 创建时间
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- 最后更新时间
    "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "uk_conn_table" UNIQUE ("connection_id", "table_name"),
    CONSTRAINT "fk_profile_conn"
        FOREIGN KEY ("connection_id") REFERENCES "meta_db_connection_configs" ("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "ai_agent_execution_traces" (
    -- 表说明：智能体执行链路步骤日志表
    -- 执行步骤主键 ID
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 关联会话链路 ID
    "trace_id" VARCHAR(64) NOT NULL,
    -- 链路步骤序号
    "step_number" INTEGER NOT NULL,
    -- 事件类型：thought、tool_call、tool_result 或 final_answer
    "event_type" VARCHAR(50) NOT NULL,
    -- 执行步骤的智能体名称
    "agent_name" VARCHAR(50),
    -- 调用的工具名称
    "tool_name" VARCHAR(100),
    -- 工具输入参数 JSON
    "tool_input" JSONB,
    -- 工具输出结果 JSON
    "tool_output" JSONB,
    -- 步骤耗时，单位毫秒
    "execution_time_ms" REAL,
    -- 步骤执行状态
    "status" VARCHAR(50) NOT NULL DEFAULT 'success',
    -- 步骤错误详情
    "error_message" TEXT,
    -- 实际使用的模型名称
    "model" VARCHAR(100),
    -- 模型温度参数
    "temperature" REAL,
    -- 输入 Token 消耗数
    "prompt_tokens" INTEGER NOT NULL DEFAULT 0,
    -- 输出 Token 消耗数
    "completion_tokens" INTEGER NOT NULL DEFAULT 0,
    -- 总 Token 消耗数
    "total_tokens" INTEGER NOT NULL DEFAULT 0,
    -- 当前 Span 唯一标识
    "span_id" VARCHAR(64),
    -- 父级 Span 唯一标识
    "parent_span_id" VARCHAR(64),
    -- 步骤额外元数据 JSON
    "meta_info" JSONB,
    -- 步骤创建时间
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "ai_agent_execution_history" (
    -- 表说明：智能体对话执行历史表
    -- 执行历史主键 ID
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 智能体 ID
    "agent_id" VARCHAR(36) NOT NULL,
    -- 关联链路 ID
    "trace_id" VARCHAR(64) NOT NULL UNIQUE,
    -- 会话 ID
    "conversation_id" VARCHAR(50),
    -- 提问用户 ID
    "user_id" VARCHAR(64),
    -- 提问用户名
    "username" VARCHAR(64),
    -- 用户提问内容
    "query" TEXT,
    -- 智能体响应摘要
    "summary" TEXT,
    -- 输入 Token 消耗数
    "prompt_tokens" INTEGER NOT NULL DEFAULT 0,
    -- 输出 Token 消耗数
    "completion_tokens" INTEGER NOT NULL DEFAULT 0,
    -- 总 Token 消耗数
    "total_tokens" INTEGER NOT NULL DEFAULT 0,
    -- 本次执行耗时，单位毫秒
    "execution_time_ms" REAL,
    -- 执行状态：success 或 failed
    "status" VARCHAR(50) NOT NULL DEFAULT 'success',
    -- 生成响应的智能体版本号
    "agent_version" VARCHAR(32),
    -- 实际使用的模型标识快照
    "model_id" VARCHAR(255),
    -- 使用的模型配置 ID
    "model_config_id" VARCHAR(36),
    -- 用户反馈：up 或 down
    "feedback" VARCHAR(10),
    -- 执行时间
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "ai_agent_access_logs" (
    -- 表说明：平台 API 访问日志表
    -- 访问日志主键 ID
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 请求链路 ID
    "trace_id" VARCHAR(64),
    -- 访问用户 ID
    "user_id" BIGINT,
    -- 访问用户名
    "user_name" VARCHAR(64),
    -- 功能点或菜单名称
    "feature_name" VARCHAR(100),
    -- 请求接口地址
    "endpoint" VARCHAR(255) NOT NULL,
    -- HTTP 请求方法
    "method" VARCHAR(10) NOT NULL,
    -- URL 查询参数
    "query_params" TEXT,
    -- HTTP 响应状态码
    "status_code" INTEGER NOT NULL,
    -- 请求处理耗时，单位毫秒
    "process_time_ms" REAL,
    -- 客户端 IP 地址
    "client_ip" VARCHAR(50),
    -- 请求参数 JSON 文本
    "request_params" TEXT,
    -- 响应内容 JSON 文本
    "response_body" TEXT,
    -- 请求错误信息
    "error_message" TEXT,
    -- 客户端 User-Agent
    "user_agent" VARCHAR(255),
    -- 访问时间
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "ai_agent_scheduler_jobs" (
    -- 表说明：APScheduler 持久化任务存储表
    -- 调度任务唯一 ID
    "id" VARCHAR(191) PRIMARY KEY,
    -- 下一次运行时间戳
    "next_run_time" DOUBLE PRECISION,
    -- 调度任务序列化状态二进制数据
    "job_state" BYTEA NOT NULL
);

CREATE TABLE IF NOT EXISTS "ai_agent_scheduled_tasks" (
    -- 表说明：智能体定时任务定义表
    -- 定时任务主键 ID
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 任务显示名称
    "name" VARCHAR(100) NOT NULL,
    -- 任务创建者 ID
    "user_id" INTEGER NOT NULL,
    -- 绑定的智能体 ID
    "agent_id" VARCHAR(50) NOT NULL,
    -- 执行结果写入的会话 ID
    "conversation_id" VARCHAR(50) NOT NULL,
    -- Cron 调度表达式
    "cron_expr" VARCHAR(50) NOT NULL,
    -- 定时执行时发送给智能体的指令
    "prompt" TEXT NOT NULL,
    -- 任务来源：web 或 agent
    "source" VARCHAR(20) NOT NULL DEFAULT 'web',
    -- 任务状态：0 停止，1 运行，2 异常
    "status" SMALLINT NOT NULL DEFAULT 1,
    -- 通知、重试等额外配置 JSON
    "config" JSONB,
    -- 累计执行次数
    "run_count" INTEGER NOT NULL DEFAULT 0,
    -- 最近一次运行链路 ID
    "last_run_id" VARCHAR(50),
    -- 上次执行时间
    "last_run_at" TIMESTAMP,
    -- 下次预计执行时间
    "next_run_at" TIMESTAMP,
    -- 创建时间
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- 最后更新时间
    "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "sys_api_tools" (
    -- 表说明：平台 API 工具注册表
    -- 工具唯一 ID
    "id" VARCHAR(36) PRIMARY KEY,
    -- 工具名称
    "name" VARCHAR(255) NOT NULL UNIQUE,
    -- 工具功能描述
    "description" TEXT,
    -- HTTP 请求方法
    "method" VARCHAR(20) NOT NULL DEFAULT 'GET',
    -- 目标 API URL 模板
    "url_template" TEXT NOT NULL,
    -- 请求头 JSON 文本
    "headers" TEXT,
    -- 工具参数 Schema JSON 文本
    "parameter_schema" TEXT,
    -- 是否启用
    "is_active" BOOLEAN NOT NULL DEFAULT TRUE,
    -- 创建时间
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- 最后更新时间
    "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "sys_mcp_servers" (
    -- 表说明：MCP 服务端注册表
    -- MCP 服务端唯一 ID
    "id" VARCHAR(36) PRIMARY KEY,
    -- MCP 服务端名称
    "server_name" VARCHAR(100) NOT NULL UNIQUE,
    -- MCP SSE 握手地址
    "sse_url" TEXT NOT NULL,
    -- 认证请求头 JSON 文本
    "auth_headers" TEXT,
    -- 启用状态：0 禁用，1 启用
    "enabled_status" SMALLINT NOT NULL DEFAULT 0,
    -- 最近一次工具同步时间
    "last_sync_at" TIMESTAMP,
    -- 创建时间
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- 最后更新时间
    "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "sys_mcp_tool_cache" (
    -- 表说明：MCP 工具发现缓存表
    -- MCP 工具缓存唯一 ID
    "id" VARCHAR(36) PRIMARY KEY,
    -- 所属 MCP 服务端 ID
    "server_id" VARCHAR(36) NOT NULL,
    -- 工具完整名称
    "tool_name" VARCHAR(255) NOT NULL,
    -- 工具描述
    "tool_description" TEXT,
    -- 工具参数 Schema JSON 文本
    "parameter_schema" TEXT,
    -- 是否发布给智能体使用
    "is_published" BOOLEAN NOT NULL DEFAULT FALSE,
    -- 创建时间
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- 最后更新时间
    "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "uk_mcp_tool_server_name" UNIQUE ("server_id", "tool_name"),
    CONSTRAINT "fk_mcp_tool_server"
        FOREIGN KEY ("server_id") REFERENCES "sys_mcp_servers" ("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "ai_chatbi_examples" (
    -- 表说明：ChatBI 优质问答与 SQL 经验案例表
    -- 案例主键 ID
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 关联执行链路 ID
    "trace_id" VARCHAR(64) NOT NULL UNIQUE,
    -- 智能体 ID
    "agent_id" VARCHAR(36) NOT NULL,
    -- 数据集 ID
    "dataset_id" INTEGER NOT NULL,
    -- 用户原始问题
    "user_query" TEXT NOT NULL,
    -- 增强后的完整问题
    "refined_query" TEXT,
    -- 问题上下文摘要
    "context_summary" TEXT,
    -- 成功执行的 SQL
    "sql_text" TEXT NOT NULL,
    -- SQL 特征元数据 JSON
    "sql_metadata" JSONB,
    -- 案例增强状态
    "enhance_status" VARCHAR(20) NOT NULL DEFAULT 'pending',
    -- 智能体回答摘要
    "ai_answer" TEXT,
    -- 反馈类型：up 或 down
    "feedback_type" VARCHAR(10) NOT NULL DEFAULT 'up',
    -- 案例审核状态
    "status" VARCHAR(20) NOT NULL DEFAULT 'pending',
    -- 负向案例错误信息
    "error_message" TEXT,
    -- 案例被引用次数
    "use_count" INTEGER NOT NULL DEFAULT 0,
    -- RAGFlow 文档 ID
    "rag_doc_id" VARCHAR(64),
    -- RAGFlow 同步状态
    "rag_sync_status" VARCHAR(20) NOT NULL DEFAULT 'pending',
    -- RAGFlow 同步错误信息
    "rag_sync_error" TEXT,
    -- 最后同步到 RAGFlow 的时间
    "rag_synced_at" TIMESTAMP,
    -- 反馈用户 ID
    "user_id" VARCHAR(64),
    -- 创建时间
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- 最后更新时间
    "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "ai_chatbi_example_usages" (
    -- 表说明：ChatBI 经验案例引用流水表
    -- 引用记录主键 ID
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 被引用案例 ID
    "example_id" BIGINT NOT NULL,
    -- 当前对话链路 ID
    "trace_id" VARCHAR(64) NOT NULL,
    -- 检索相似度
    "similarity" REAL,
    -- 引用时间
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "portal_saved_reports" (
    -- 表说明：ChatBI 已保存黄金报表表
    -- 保存报表唯一 ID
    "id" VARCHAR(64) PRIMARY KEY,
    -- 报表标题
    "title" VARCHAR(100) NOT NULL,
    -- 报表说明
    "description" VARCHAR(500),
    -- 报表执行 SQL
    "sql_content" TEXT NOT NULL,
    -- 关联数据集 ID
    "dataset_id" BIGINT,
    -- 报表使用的数据源
    "data_source" VARCHAR(100) NOT NULL,
    -- 生成报表的原始问题
    "original_query" TEXT,
    -- 报表 SQL 模式
    "mode" VARCHAR(32) NOT NULL DEFAULT 'static_sql',
    -- 参数化 SQL 模板
    "sql_template" TEXT,
    -- 参数定义 Schema JSON
    "params_schema" JSONB,
    -- 默认参数 JSON
    "default_params" JSONB,
    -- 分析模式
    "analysis_mode" VARCHAR(32) NOT NULL DEFAULT 'manual',
    -- 报表标签 JSON
    "tags" JSONB,
    -- 报表所有者用户 ID
    "owner_user_id" BIGINT NOT NULL,
    -- 报表所有者名称快照
    "owner_name" VARCHAR(100),
    -- 可见范围
    "visibility" VARCHAR(32) NOT NULL DEFAULT 'private',
    -- 报表状态
    "status" VARCHAR(32) NOT NULL DEFAULT 'active',
    -- 最近运行时间
    "last_run_at" TIMESTAMP,
    -- 最近成功运行时间
    "last_success_at" TIMESTAMP,
    -- 最近一次运行错误
    "last_error" TEXT,
    -- 创建时间
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- 最后更新时间
    "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "fk_portal_saved_reports_owner"
        FOREIGN KEY ("owner_user_id") REFERENCES "ai_agent_users" ("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "portal_saved_report_shares" (
    -- 表说明：已保存报表共享对象表
    -- 共享记录主键 ID
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 已保存报表 ID
    "report_id" VARCHAR(64) NOT NULL,
    -- 共享对象类型
    "target_type" VARCHAR(16) NOT NULL,
    -- 共享对象业务 ID
    "target_id" BIGINT NOT NULL,
    -- 共享权限
    "permission" VARCHAR(16) NOT NULL DEFAULT 'run',
    -- 共享创建者用户 ID
    "created_by" BIGINT NOT NULL,
    -- 创建时间
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "ux_portal_saved_report_share_target"
        UNIQUE ("report_id", "target_type", "target_id"),
    CONSTRAINT "fk_portal_saved_report_shares_report"
        FOREIGN KEY ("report_id") REFERENCES "portal_saved_reports" ("id") ON DELETE CASCADE,
    CONSTRAINT "fk_portal_saved_report_shares_created_by"
        FOREIGN KEY ("created_by") REFERENCES "ai_agent_users" ("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "portal_saved_report_user_prefs" (
    -- 表说明：用户已保存报表偏好表
    -- 偏好记录主键 ID
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 已保存报表 ID
    "report_id" VARCHAR(64) NOT NULL,
    -- 用户 ID
    "user_id" BIGINT NOT NULL,
    -- 是否收藏
    "is_favorite" BOOLEAN NOT NULL DEFAULT FALSE,
    -- 置顶时间
    "pinned_at" TIMESTAMP,
    -- 最近浏览时间
    "last_viewed_at" TIMESTAMP,
    -- 用户运行次数
    "run_count" INTEGER NOT NULL DEFAULT 0,
    -- 最近运行时间
    "last_run_at" TIMESTAMP,
    -- 创建时间
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- 最后更新时间
    "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "ux_portal_saved_report_user_pref" UNIQUE ("report_id", "user_id"),
    CONSTRAINT "fk_saved_report_user_pref_report"
        FOREIGN KEY ("report_id") REFERENCES "portal_saved_reports" ("id") ON DELETE CASCADE,
    CONSTRAINT "fk_saved_report_user_pref_user"
        FOREIGN KEY ("user_id") REFERENCES "ai_agent_users" ("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "portal_saved_report_runs" (
    -- 表说明：已保存报表运行历史与结果快照表
    -- 运行记录主键 ID
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 已保存报表 ID
    "report_id" VARCHAR(64) NOT NULL,
    -- 本次运行用户 ID
    "user_id" BIGINT NOT NULL,
    -- 触发类型：manual 或 scheduled
    "trigger_type" VARCHAR(32) NOT NULL DEFAULT 'manual',
    -- 关联定时任务 ID
    "task_id" BIGINT,
    -- 运行状态
    "status" VARCHAR(16) NOT NULL DEFAULT 'running',
    -- 解析后的运行参数 JSON
    "resolved_params" JSONB,
    -- 本次实际执行的 SQL
    "executed_sql" TEXT,
    -- 本次运行使用的数据源
    "data_source" VARCHAR(100),
    -- 本次运行使用的数据集名称
    "dataset_name" VARCHAR(255),
    -- 查询结果总行数
    "row_count" INTEGER,
    -- 实际保存的结果快照行数
    "snapshot_row_count" INTEGER NOT NULL DEFAULT 0,
    -- 结果快照 JSON
    "result_snapshot" JSONB,
    -- 数据权限处理摘要 JSON
    "permission_notice" JSONB,
    -- 运行耗时，单位毫秒
    "duration_ms" INTEGER,
    -- 面向用户的运行错误说明
    "error_message" TEXT,
    -- 运行开始时间
    "started_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- 运行完成或失败时间
    "finished_at" TIMESTAMP,
    CONSTRAINT "fk_portal_saved_report_runs_report"
        FOREIGN KEY ("report_id") REFERENCES "portal_saved_reports" ("id") ON DELETE CASCADE,
    CONSTRAINT "fk_portal_saved_report_runs_user"
        FOREIGN KEY ("user_id") REFERENCES "ai_agent_users" ("id")
);

CREATE TABLE IF NOT EXISTS "portal_saved_report_subscriptions" (
    -- 表说明：黄金报表定时订阅配置表
    -- 订阅主键 ID
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 黄金报表 ID
    "report_id" VARCHAR(64) NOT NULL UNIQUE,
    -- 订阅创建人与执行用户 ID
    "user_id" BIGINT NOT NULL,
    -- 频率类型：daily、weekly、monthly 或 cron
    "schedule_type" VARCHAR(16) NOT NULL,
    -- 标准 Cron 表达式
    "cron_expr" VARCHAR(64) NOT NULL,
    -- 调度时区
    "timezone" VARCHAR(64) NOT NULL DEFAULT 'Asia/Shanghai',
    -- 定时运行报表参数 JSON
    "params" JSONB,
    -- 是否启用 AI 智能分析
    "ai_analysis_enabled" BOOLEAN NOT NULL DEFAULT TRUE,
    -- 订阅级 AI 分析要求
    "analysis_instruction" TEXT,
    -- 成功时是否生成通知
    "notify_on_success" BOOLEAN NOT NULL DEFAULT FALSE,
    -- 失败时是否生成通知
    "notify_on_failure" BOOLEAN NOT NULL DEFAULT TRUE,
    -- 外部通知渠道 JSON
    "external_channels" JSONB,
    -- 版本化告警条件 JSON
    "alert_condition" JSONB,
    -- 最近告警基线与命中状态 JSON
    "alert_state" JSONB,
    -- 订阅状态
    "status" VARCHAR(16) NOT NULL DEFAULT 'active',
    -- 连续失败次数
    "consecutive_failures" INTEGER NOT NULL DEFAULT 0,
    -- 最近一次运行记录 ID
    "last_run_id" BIGINT,
    -- 最近一次运行时间
    "last_run_at" TIMESTAMP,
    -- 下一次计划运行时间
    "next_run_at" TIMESTAMP,
    -- 最近一次错误信息
    "last_error" TEXT,
    -- 创建时间
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- 最后更新时间
    "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "fk_portal_saved_report_subscriptions_report"
        FOREIGN KEY ("report_id") REFERENCES "portal_saved_reports" ("id") ON DELETE CASCADE,
    CONSTRAINT "fk_portal_saved_report_subscriptions_user"
        FOREIGN KEY ("user_id") REFERENCES "ai_agent_users" ("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "portal_saved_report_digest_deliveries" (
    -- 表说明：黄金报表智能简报推送审计表
    -- 推送审计主键 ID
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 报表运行记录 ID
    "run_id" BIGINT NOT NULL,
    -- 报表订阅 ID
    "subscription_id" BIGINT NOT NULL,
    -- 推送渠道：inbox、dingtalk、wechat_work 或 email
    "channel" VARCHAR(32) NOT NULL,
    -- 结构化智能简报 JSON
    "digest_payload" JSONB,
    -- 告警判断与触发证据 JSON
    "trigger_evidence" JSONB,
    -- 实际发送的消息标题
    "title" VARCHAR(200) NOT NULL,
    -- 实际发送的消息正文
    "content" TEXT NOT NULL,
    -- 发送状态：pending、success 或 failed
    "status" VARCHAR(16) NOT NULL DEFAULT 'pending',
    -- 渠道发送失败原因
    "error_message" TEXT,
    -- AI 生成状态
    "ai_status" VARCHAR(16) NOT NULL DEFAULT 'disabled',
    -- 发送完成时间
    "sent_at" TIMESTAMP,
    -- 审计记录创建时间
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "fk_saved_report_digest_run"
        FOREIGN KEY ("run_id") REFERENCES "portal_saved_report_runs" ("id") ON DELETE CASCADE,
    CONSTRAINT "fk_saved_report_digest_subscription"
        FOREIGN KEY ("subscription_id") REFERENCES "portal_saved_report_subscriptions" ("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "portal_notifications" (
    -- 表说明：用户站内通知表
    -- 通知主键 ID
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 通知接收用户 ID
    "user_id" BIGINT NOT NULL,
    -- 通知业务分类
    "category" VARCHAR(32) NOT NULL DEFAULT 'saved_report',
    -- 通知等级：success、warning、error 或 info
    "level" VARCHAR(16) NOT NULL DEFAULT 'info',
    -- 通知标题
    "title" VARCHAR(200) NOT NULL,
    -- 通知摘要内容
    "content" TEXT,
    -- 关联资源类型
    "resource_type" VARCHAR(32),
    -- 关联资源 ID
    "resource_id" VARCHAR(64),
    -- 通知跳转和展示摘要 JSON
    "metadata" JSONB,
    -- 已读时间，为空表示未读
    "read_at" TIMESTAMP,
    -- 通知创建时间
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "fk_portal_notifications_user"
        FOREIGN KEY ("user_id") REFERENCES "ai_agent_users" ("id")
);

CREATE TABLE IF NOT EXISTS "chatbi_briefs" (
    -- 表说明：ChatBI 证据化业务简报表
    -- 业务简报唯一 ID
    "id" VARCHAR(64) PRIMARY KEY,
    -- 简报所属用户 ID
    "owner_user_id" BIGINT NOT NULL,
    -- 来源 ChatBI 会话 ID
    "conversation_id" VARCHAR(128) NOT NULL,
    -- 来源结构化结果 ID
    "result_id" VARCHAR(64),
    -- 业务简报标题
    "title" VARCHAR(200) NOT NULL,
    -- 简报结构化内容与证据 JSON
    "brief_payload" JSONB NOT NULL,
    -- 简报 Markdown 正文
    "markdown_content" TEXT NOT NULL,
    -- 生成文件下载信息 JSON
    "artifact_payload" JSONB,
    -- 简报创建时间
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "fk_chatbi_briefs_owner"
        FOREIGN KEY ("owner_user_id") REFERENCES "ai_agent_users" ("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "knowledge_base_metadata" (
    -- 表说明：平台侧知识库扩展元数据表
    -- 知识库元数据主键 ID
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- RAGFlow Dataset ID
    "ragflow_dataset_id" VARCHAR(64) NOT NULL UNIQUE,
    -- 知识库名称快照
    "name" VARCHAR(255) NOT NULL,
    -- 知识库描述快照
    "description" TEXT,
    -- 业务归属或负责人
    "owner" VARCHAR(100),
    -- 可见性：private、team 或 public
    "visibility" VARCHAR(32) NOT NULL DEFAULT 'private',
    -- 平台侧标签 JSON
    "tags" JSONB,
    -- 平台侧备注
    "notes" TEXT,
    -- 知识库扩展配置 JSON
    "extra_config" JSONB,
    -- 知识库状态：active、deleted 或 missing
    "status" VARCHAR(32) NOT NULL DEFAULT 'active',
    -- 创建人
    "created_by" VARCHAR(64),
    -- 最后更新人
    "updated_by" VARCHAR(64),
    -- 创建时间
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- 最后更新时间
    "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "knowledge_base_metrics" (
    -- 表说明：知识库与文档每日运营指标表
    -- 指标记录主键 ID
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 统计日期
    "metric_date" DATE NOT NULL,
    -- 统计对象类型：dataset 或 document
    "target_type" VARCHAR(32) NOT NULL,
    -- 统计对象 ID
    "target_id" VARCHAR(64) NOT NULL,
    -- 统计对象名称快照
    "target_name" VARCHAR(255),
    -- 被引用次数
    "citation_count" INTEGER NOT NULL DEFAULT 0,
    -- 被搜索或召回次数
    "search_count" INTEGER NOT NULL DEFAULT 0,
    -- 创建时间
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- 最后更新时间
    "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "uix_kb_metric_date_target" UNIQUE ("metric_date", "target_type", "target_id")
);

CREATE TABLE IF NOT EXISTS "ai_agent_quota_policies" (
    -- 表说明：用户、角色和系统 Token 额度策略表
    -- 额度策略主键 ID
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 策略范围：user、role 或 system
    "scope_type" VARCHAR(20) NOT NULL,
    -- 用户 ID 或角色 ID
    "scope_id" BIGINT,
    -- 额度周期
    "period" VARCHAR(20) NOT NULL DEFAULT 'monthly',
    -- Token 上限，为空表示不限额
    "limit_tokens" BIGINT,
    -- 是否启用策略
    "enabled" BOOLEAN NOT NULL DEFAULT TRUE,
    -- 超额动作
    "action_on_exceed" VARCHAR(20) NOT NULL DEFAULT 'block',
    -- 创建时间
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- 最后更新时间
    "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "uk_quota_scope_period" UNIQUE ("scope_type", "scope_id", "period")
);

CREATE TABLE IF NOT EXISTS "user_notification_configs" (
    -- 表说明：用户个人通知渠道配置表
    -- 通知配置主键 ID
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 用户 ID
    "user_id" BIGINT NOT NULL,
    -- 通知渠道类型
    "channel_type" VARCHAR(50) NOT NULL,
    -- 通知渠道参数 JSON 文本
    "config_json" TEXT NOT NULL,
    -- 创建时间
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- 最后更新时间
    "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "ux_user_notification_channel" UNIQUE ("user_id", "channel_type"),
    CONSTRAINT "fk_user_notification_config_user"
        FOREIGN KEY ("user_id") REFERENCES "ai_agent_users" ("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "ai_agent_scenario_instances" (
    -- 表说明：场景模板交付实例表
    -- 交付实例唯一 ID
    "id" VARCHAR(36) PRIMARY KEY,
    -- 场景模板 ID
    "template_id" VARCHAR(100) NOT NULL,
    -- 场景模板名称快照
    "template_name" VARCHAR(100) NOT NULL,
    -- 交付后关联的智能体 ID
    "agent_id" VARCHAR(36) NOT NULL,
    -- 智能体标识快照
    "agent_name" VARCHAR(100) NOT NULL,
    -- 交付实例显示名称
    "display_name" VARCHAR(100) NOT NULL,
    -- 业务负责人或交付负责人
    "owner" VARCHAR(100),
    -- 交付状态
    "status" VARCHAR(32) NOT NULL DEFAULT 'installed',
    -- 资源绑定快照 JSON
    "resource_bindings" JSONB,
    -- 缺失资源清单 JSON
    "missing_resources" JSONB,
    -- 本次交付物清单 JSON
    "deliverables" JSONB,
    -- 验收标准快照 JSON
    "acceptance_criteria" JSONB,
    -- 后续动作 JSON
    "next_steps" JSONB,
    -- 创建人
    "created_by" VARCHAR(64),
    -- 最后更新人
    "updated_by" VARCHAR(64),
    -- 创建时间
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- 最后更新时间
    "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "uix_scenario_template_agent" UNIQUE ("template_id", "agent_id")
);

CREATE TABLE IF NOT EXISTS "ai_agent_scenario_install_runs" (
    -- 表说明：场景模板安装运行记录表
    -- 安装运行记录唯一 ID
    "id" VARCHAR(36) PRIMARY KEY,
    -- 交付实例 ID
    "instance_id" VARCHAR(36),
    -- 场景模板 ID
    "template_id" VARCHAR(100) NOT NULL,
    -- 关联智能体 ID
    "agent_id" VARCHAR(36),
    -- 安装状态：success、blocked 或 failed
    "status" VARCHAR(32) NOT NULL,
    -- 安装预检结果 JSON
    "precheck_result" JSONB,
    -- 安装结果 JSON
    "install_result" JSONB,
    -- 失败或阻断原因
    "error_message" TEXT,
    -- 执行人
    "created_by" VARCHAR(64),
    -- 运行创建时间
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Indexes consolidated from the current MySQL migration chain.
CREATE INDEX IF NOT EXISTS "idx_user_org_path" ON "ai_agent_users" ("org_path");
CREATE INDEX IF NOT EXISTS "idx_system_configs_category" ON "system_configs" ("category");
CREATE INDEX IF NOT EXISTS "idx_system_configs_key_updated" ON "system_configs" ("key", "updated_at");
CREATE INDEX IF NOT EXISTS "idx_system_config_history_key_created" ON "system_config_history" ("config_key", "created_at");
CREATE INDEX IF NOT EXISTS "idx_system_config_history_changed_by_created" ON "system_config_history" ("changed_by", "created_at");
CREATE INDEX IF NOT EXISTS "idx_system_config_history_type_created" ON "system_config_history" ("change_type", "created_at");
CREATE INDEX IF NOT EXISTS "idx_slash_commands_sort_created" ON "slash_commands" ("sort_order", "created_at");
CREATE INDEX IF NOT EXISTS "idx_slash_commands_created_by_created" ON "slash_commands" ("created_by", "created_at");

CREATE INDEX IF NOT EXISTS "idx_ai_agents_system_created" ON "ai_agents" ("is_system", "created_at");
CREATE INDEX IF NOT EXISTS "idx_ai_agents_owner_created" ON "ai_agents" ("owner_group", "created_at");
CREATE INDEX IF NOT EXISTS "idx_ai_agent_versions_agent_status" ON "ai_agent_versions" ("agent_id", "status");
CREATE INDEX IF NOT EXISTS "idx_ai_agent_versions_agent_version" ON "ai_agent_versions" ("agent_id", "version_number");
CREATE INDEX IF NOT EXISTS "idx_ai_agent_versions_status_created" ON "ai_agent_versions" ("status", "created_at");

CREATE INDEX IF NOT EXISTS "idx_user_role_user" ON "ai_agent_user_role_relations" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_user_role_role" ON "ai_agent_user_role_relations" ("role_id");
CREATE INDEX IF NOT EXISTS "idx_resource_permission_user_type" ON "ai_agent_resource_permissions" ("user_id", "resource_type");
CREATE INDEX IF NOT EXISTS "idx_resource_permission_role_type" ON "ai_agent_resource_permissions" ("role_id", "resource_type");
CREATE INDEX IF NOT EXISTS "idx_resource_permission_resource" ON "ai_agent_resource_permissions" ("resource_type", "resource_id");

CREATE INDEX IF NOT EXISTS "idx_meta_dataset_data_source_created" ON "meta_datasets" ("data_source", "created_at");
CREATE INDEX IF NOT EXISTS "idx_meta_dataset_rag_status" ON "meta_datasets" ("rag_sync_status");
CREATE INDEX IF NOT EXISTS "idx_meta_tables_dataset_created" ON "meta_tables" ("dataset_id", "created_at");
CREATE INDEX IF NOT EXISTS "idx_meta_tables_status_created" ON "meta_tables" ("status", "created_at");
CREATE INDEX IF NOT EXISTS "idx_meta_columns_table_created" ON "meta_columns" ("table_id", "created_at");
CREATE INDEX IF NOT EXISTS "idx_meta_columns_type_created" ON "meta_columns" ("type", "created_at");
CREATE INDEX IF NOT EXISTS "idx_meta_metrics_dataset_created" ON "meta_metrics" ("dataset_id", "created_at");
CREATE INDEX IF NOT EXISTS "idx_meta_metrics_name_created" ON "meta_metrics" ("name", "created_at");
CREATE INDEX IF NOT EXISTS "idx_meta_changelog_resource" ON "meta_changelog" ("resource_type", "resource_id");
CREATE INDEX IF NOT EXISTS "idx_meta_changelog_user" ON "meta_changelog" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_meta_changelog_created" ON "meta_changelog" ("created_at");
CREATE INDEX IF NOT EXISTS "idx_meta_changelog_operation" ON "meta_changelog" ("operation");
CREATE INDEX IF NOT EXISTS "idx_meta_connection_created_by" ON "meta_db_connection_configs" ("created_by");

CREATE INDEX IF NOT EXISTS "idx_trace_id" ON "ai_agent_execution_traces" ("trace_id");
CREATE INDEX IF NOT EXISTS "idx_trace_created" ON "ai_agent_execution_traces" ("trace_id", "created_at");
CREATE INDEX IF NOT EXISTS "idx_event_created" ON "ai_agent_execution_traces" ("event_type", "created_at");
CREATE INDEX IF NOT EXISTS "idx_tool_created" ON "ai_agent_execution_traces" ("tool_name", "created_at");
CREATE INDEX IF NOT EXISTS "idx_trace_status_created" ON "ai_agent_execution_traces" ("status", "created_at");
CREATE INDEX IF NOT EXISTS "idx_trace_span_parent" ON "ai_agent_execution_traces" ("span_id", "parent_span_id");
CREATE INDEX IF NOT EXISTS "idx_history_agent_created" ON "ai_agent_execution_history" ("agent_id", "created_at");
CREATE INDEX IF NOT EXISTS "idx_history_user_created" ON "ai_agent_execution_history" ("user_id", "created_at");
CREATE INDEX IF NOT EXISTS "idx_history_status_created" ON "ai_agent_execution_history" ("status", "created_at");
CREATE INDEX IF NOT EXISTS "idx_history_model_id" ON "ai_agent_execution_history" ("model_id");
CREATE INDEX IF NOT EXISTS "idx_history_model_config_id" ON "ai_agent_execution_history" ("model_config_id");
CREATE INDEX IF NOT EXISTS "idx_access_log_trace" ON "ai_agent_access_logs" ("trace_id");
CREATE INDEX IF NOT EXISTS "idx_access_log_status_created" ON "ai_agent_access_logs" ("status_code", "created_at");
CREATE INDEX IF NOT EXISTS "idx_access_log_endpoint_created" ON "ai_agent_access_logs" ("endpoint", "created_at");
CREATE INDEX IF NOT EXISTS "idx_access_log_feature" ON "ai_agent_access_logs" ("feature_name");
CREATE INDEX IF NOT EXISTS "idx_scheduler_jobs_next_run_time" ON "ai_agent_scheduler_jobs" ("next_run_time");
CREATE INDEX IF NOT EXISTS "idx_scheduled_tasks_user" ON "ai_agent_scheduled_tasks" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_scheduled_tasks_status" ON "ai_agent_scheduled_tasks" ("status");

CREATE INDEX IF NOT EXISTS "idx_sys_api_tools_active" ON "sys_api_tools" ("is_active");
CREATE INDEX IF NOT EXISTS "idx_mcp_tool_published" ON "sys_mcp_tool_cache" ("is_published");
CREATE INDEX IF NOT EXISTS "idx_chatbi_example_agent_dataset" ON "ai_chatbi_examples" ("agent_id", "dataset_id");
CREATE INDEX IF NOT EXISTS "idx_chatbi_example_status" ON "ai_chatbi_examples" ("status");
CREATE INDEX IF NOT EXISTS "idx_chatbi_example_rag_sync" ON "ai_chatbi_examples" ("rag_sync_status");
CREATE INDEX IF NOT EXISTS "idx_chatbi_example_usage_example" ON "ai_chatbi_example_usages" ("example_id");
CREATE INDEX IF NOT EXISTS "idx_chatbi_example_usage_trace" ON "ai_chatbi_example_usages" ("trace_id");

CREATE INDEX IF NOT EXISTS "idx_saved_reports_owner_updated" ON "portal_saved_reports" ("owner_user_id", "updated_at");
CREATE INDEX IF NOT EXISTS "idx_saved_reports_visibility" ON "portal_saved_reports" ("visibility");
CREATE INDEX IF NOT EXISTS "idx_saved_report_shares_target" ON "portal_saved_report_shares" ("target_type", "target_id");
CREATE INDEX IF NOT EXISTS "idx_saved_report_shares_report" ON "portal_saved_report_shares" ("report_id");
CREATE INDEX IF NOT EXISTS "idx_saved_report_shares_created_by" ON "portal_saved_report_shares" ("created_by");
CREATE INDEX IF NOT EXISTS "idx_saved_report_prefs_user" ON "portal_saved_report_user_prefs" ("user_id", "pinned_at", "last_run_at");
CREATE INDEX IF NOT EXISTS "idx_saved_report_runs_report_started" ON "portal_saved_report_runs" ("report_id", "started_at");
CREATE INDEX IF NOT EXISTS "idx_saved_report_runs_user_started" ON "portal_saved_report_runs" ("user_id", "started_at");
CREATE INDEX IF NOT EXISTS "idx_saved_report_runs_task" ON "portal_saved_report_runs" ("task_id");
CREATE INDEX IF NOT EXISTS "idx_saved_report_runs_status_started" ON "portal_saved_report_runs" ("status", "started_at");
CREATE INDEX IF NOT EXISTS "idx_saved_report_digest_run" ON "portal_saved_report_digest_deliveries" ("run_id");
CREATE INDEX IF NOT EXISTS "idx_saved_report_digest_subscription_created"
    ON "portal_saved_report_digest_deliveries" ("subscription_id", "created_at");
CREATE INDEX IF NOT EXISTS "idx_portal_notifications_user_created" ON "portal_notifications" ("user_id", "created_at");
CREATE INDEX IF NOT EXISTS "idx_portal_notifications_user_read" ON "portal_notifications" ("user_id", "read_at");
CREATE INDEX IF NOT EXISTS "idx_chatbi_briefs_owner_created" ON "chatbi_briefs" ("owner_user_id", "created_at");
CREATE INDEX IF NOT EXISTS "idx_chatbi_briefs_conversation" ON "chatbi_briefs" ("conversation_id");
CREATE INDEX IF NOT EXISTS "idx_chatbi_briefs_result" ON "chatbi_briefs" ("result_id");

CREATE INDEX IF NOT EXISTS "idx_kb_status" ON "knowledge_base_metadata" ("status");
CREATE INDEX IF NOT EXISTS "idx_kb_owner" ON "knowledge_base_metadata" ("owner");
CREATE INDEX IF NOT EXISTS "idx_kb_created_by" ON "knowledge_base_metadata" ("created_by");
CREATE INDEX IF NOT EXISTS "idx_kb_metrics_date" ON "knowledge_base_metrics" ("metric_date");
CREATE INDEX IF NOT EXISTS "idx_kb_metrics_target" ON "knowledge_base_metrics" ("target_type", "target_id");
CREATE INDEX IF NOT EXISTS "idx_quota_scope" ON "ai_agent_quota_policies" ("scope_type", "scope_id");
CREATE INDEX IF NOT EXISTS "idx_user_notification_user" ON "user_notification_configs" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_scenario_instance_template" ON "ai_agent_scenario_instances" ("template_id");
CREATE INDEX IF NOT EXISTS "idx_scenario_instance_agent" ON "ai_agent_scenario_instances" ("agent_id");
CREATE INDEX IF NOT EXISTS "idx_scenario_install_instance" ON "ai_agent_scenario_install_runs" ("instance_id");
CREATE INDEX IF NOT EXISTS "idx_scenario_install_template" ON "ai_agent_scenario_install_runs" ("template_id");
CREATE INDEX IF NOT EXISTS "idx_scenario_install_agent" ON "ai_agent_scenario_install_runs" ("agent_id");
CREATE INDEX IF NOT EXISTS "idx_db_profile_tasks_connection" ON "db_profile_tasks" ("connection_id");
CREATE INDEX IF NOT EXISTS "idx_db_table_profiles_connection" ON "db_table_profiles" ("connection_id");

-- Safe, non-secret bootstrap values. Deployment-specific credentials remain blank.
INSERT INTO "system_configs" ("key", "value", "description", "category", "is_secret") VALUES
    ('llm_model_name', 'DeepSeek-V3.2', '系统默认模型', 'llm', FALSE),
    ('llm_temperature', '0.0', 'LLM 温度参数', 'llm', FALSE),
    ('external_sql_api_url', 'https://yunshu-api.yovole.net/api/v1/sql/execute', '外部 SQL 执行 API 地址', 'data_api', FALSE),
    ('external_sql_api_key', '', '外部 SQL API 鉴权 Key', 'data_api', TRUE),
    ('agent_max_iterations', '20', '智能体最大思考/调用工具轮数', 'agent', FALSE),
    ('data_api_timeout_seconds', '60.0', '数据查数接口 SQL 执行超时时间（秒）', 'data_api', FALSE),
    ('schema_api_timeout_seconds', '10.0', '元数据获取接口超时时间（秒）', 'data_api', FALSE),
    ('metadata_provider', 'local', '元数据提供者类型', 'metadata', FALSE),
    ('ragflow_api_url', '', 'RAGFlow 服务地址', 'metadata', FALSE),
    ('ragflow_api_key', '', 'RAGFlow API Key', 'metadata', TRUE),
    ('audit_log_retention_days', '90', '系统日志和智能体步骤 Trace 保留期限天数', 'other', FALSE),
    ('chatbi_sample_knowledge_base', '', 'ChatBI 优质 SQL 案例 RAGFlow 数据集 ID', 'agent', FALSE)
ON CONFLICT ("key") DO NOTHING;

INSERT INTO "memory_service_configs" ("key", "value", "description", "is_secret") VALUES
    ('memory_service_enabled', 'true', '记忆服务总开关', FALSE),
    ('memory_summary_enabled', 'true', '是否写入会话摘要与向量索引', FALSE),
    ('memory_embedding_base_url', '', 'Embedding API Base URL', FALSE),
    ('memory_embedding_api_key', '', 'Embedding API Key', TRUE),
    ('memory_embedding_model', 'text-embedding-3-small', 'Embedding 模型名称', FALSE),
    ('memory_embedding_dimensions', '1536', '向量维度', FALSE),
    ('memory_summary_max_sessions', '50', '每用户最多保留的会话摘要条数', FALSE),
    ('memory_summary_ttl_days', '30', '会话摘要 Redis 文档 TTL（天）', FALSE),
    ('memory_history_ttl_days', '7', '会话 history LIST TTL（天）', FALSE),
    ('memory_summarize_debounce_turns', '3', '触发摘要合并的累计对话轮数', FALSE),
    ('memory_summarize_debounce_seconds', '300', '同会话两次摘要最短间隔（秒）', FALSE),
    ('memory_search_knn_top_k', '5', 'memory_search 默认 Top K', FALSE),
    ('memory_summarize_min_assistant_chars', '30', '跳过摘要的最短 assistant 回复长度', FALSE)
ON CONFLICT ("key") DO NOTHING;

INSERT INTO "slash_commands" ("label", "command", "sort_order")
SELECT seed."label", seed."command", seed."sort_order"
FROM (VALUES
    ('🏢 机房列表', '查一下所有机房的列表', 10),
    ('⚠️ 异常告警', '最近24小时有哪些异常告警？', 20),
    ('📊 PUE统计', '统计华东一号机房昨天的 PUE 指标', 30),
    ('📈 事件对比', '对比华东和华南机房最近的事件数量', 40),
    ('请假申请', '我要请假', 50)
) AS seed("label", "command", "sort_order")
WHERE NOT EXISTS (
    SELECT 1
    FROM "slash_commands" existing
    WHERE existing."label" = seed."label"
      AND existing."command" = seed."command"
);

INSERT INTO "ai_models" ("id", "name", "model_id", "provider", "type", "is_active") VALUES
    ('deepseek-v3.2', 'DeepSeek-V3.2', 'DeepSeek-V3.2', 'deepseek', 'llm', TRUE)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "ai_agents" (
    "id", "name", "display_name", "description", "capabilities", "agent_type", "is_system", "is_enabled"
) VALUES
    ('sys-agent-chatbi', 'chat-bi', '数据智能助手', '专注于数据查询、SQL 生成与报表分析。', '["data_query", "sql_generation", "reporting"]'::jsonb, 'CHATBI', TRUE, TRUE),
    ('sys-agent-metadata', 'metadata-specialist', '元数据专家', '专注于数据库 DDL 解析与元数据治理。', '["metadata_parsing", "ddl_analysis", "schema_governance"]'::jsonb, 'GENERAL', TRUE, TRUE),
    ('sys-agent-kb', 'knowledge-base', '知识库助手', '专注于企业知识库检索问答。', '["knowledge_retrieval", "document_search", "qa"]'::jsonb, 'KNOWLEDGE_BASE', TRUE, TRUE),
    ('sys-agent-chat', 'main', '主助手(Main)', '处理通用问答、代码辅助和无法明确分类的请求。', '["general_chat", "coding", "creative_writing"]'::jsonb, 'GENERAL', TRUE, TRUE)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "ai_agent_versions" (
    "id", "agent_id", "version_number", "model_name", "system_prompt", "tools", "status", "comment"
) VALUES
    ('v1-chatbi', 'sys-agent-chatbi', 1, 'DeepSeek-V3.2', '你是南孜智能数据分析助手。请基于平台提供的 Schema 和工具结果回答问题，不要编造数据。', '["get_dataset_schema", "execute_sql_query"]'::jsonb, 'PUBLISHED', 'PostgreSQL baseline bootstrap'),
    ('v1-metadata', 'sys-agent-metadata', 1, 'DeepSeek-V3.2', '你是元数据专家，负责将 DDL 和业务描述整理为标准化元数据。', '[]'::jsonb, 'PUBLISHED', 'PostgreSQL baseline bootstrap'),
    ('v1-kb', 'sys-agent-kb', 1, 'DeepSeek-V3.2', '你是知识库助手，回答必须以检索到的企业知识为依据。', '[]'::jsonb, 'PUBLISHED', 'PostgreSQL baseline bootstrap'),
    ('v1-chat', 'sys-agent-chat', 1, 'DeepSeek-V3.2', '你是南孜通用助手，请清晰、准确地回答用户问题。', '[]'::jsonb, 'PUBLISHED', 'PostgreSQL baseline bootstrap')
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "ai_agent_resource_permissions" ("resource_type", "resource_id", "enabled")
SELECT seed."resource_type", seed."resource_id", seed."enabled"
FROM (VALUES
    ('menu', 'menu:knowledge_management', TRUE),
    ('menu', 'menu:memory_management', TRUE),
    ('menu', 'menu:chatbi_examples', TRUE)
) AS seed("resource_type", "resource_id", "enabled")
WHERE NOT EXISTS (
    SELECT 1
    FROM "ai_agent_resource_permissions" existing
    WHERE existing."resource_type" = seed."resource_type"
      AND existing."resource_id" = seed."resource_id"
);

-- 中文表与字段说明，供数据源摸排、元数据展示和数据库管理工具直接读取。
COMMENT ON TABLE "ai_agent_users" IS '智能体平台用户表';
COMMENT ON COLUMN "ai_agent_users"."id" IS '用户主键 ID';
COMMENT ON COLUMN "ai_agent_users"."user_name" IS '登录用户名';
COMMENT ON COLUMN "ai_agent_users"."real_name" IS '用户真实姓名';
COMMENT ON COLUMN "ai_agent_users"."api_key_encrypted" IS '加密存储的 API Key';
COMMENT ON COLUMN "ai_agent_users"."api_key_hash" IS 'API Key 的 SHA256 哈希值';
COMMENT ON COLUMN "ai_agent_users"."password_hash" IS '用户密码哈希值';
COMMENT ON COLUMN "ai_agent_users"."role" IS '平台角色：admin 或 user';
COMMENT ON COLUMN "ai_agent_users"."dept_id" IS '部门唯一标识 ID';
COMMENT ON COLUMN "ai_agent_users"."dept_code" IS '部门代码';
COMMENT ON COLUMN "ai_agent_users"."org_path" IS '组织结构全路径';
COMMENT ON COLUMN "ai_agent_users"."extra_data" IS '用户扩展数据，保存 JSON 文本';
COMMENT ON COLUMN "ai_agent_users"."remark" IS '用户备注';
COMMENT ON COLUMN "ai_agent_users"."status" IS '用户状态：1 启用，0 停用';
COMMENT ON COLUMN "ai_agent_users"."created_at" IS '创建时间';
COMMENT ON COLUMN "ai_agent_users"."updated_at" IS '最后更新时间';

COMMENT ON TABLE "system_configs" IS '系统动态配置表';
COMMENT ON COLUMN "system_configs"."key" IS '配置键名';
COMMENT ON COLUMN "system_configs"."value" IS '配置值';
COMMENT ON COLUMN "system_configs"."description" IS '配置说明';
COMMENT ON COLUMN "system_configs"."category" IS '配置分类';
COMMENT ON COLUMN "system_configs"."is_secret" IS '是否为敏感配置';
COMMENT ON COLUMN "system_configs"."created_at" IS '创建时间';
COMMENT ON COLUMN "system_configs"."updated_at" IS '最后更新时间';

COMMENT ON TABLE "system_config_history" IS '系统配置变更历史审计表';
COMMENT ON COLUMN "system_config_history"."id" IS '变更记录主键 ID';
COMMENT ON COLUMN "system_config_history"."config_key" IS '被变更的配置键名';
COMMENT ON COLUMN "system_config_history"."old_value" IS '变更前的配置值';
COMMENT ON COLUMN "system_config_history"."new_value" IS '变更后的配置值';
COMMENT ON COLUMN "system_config_history"."description" IS '变更描述或备注';
COMMENT ON COLUMN "system_config_history"."changed_by" IS '变更操作人';
COMMENT ON COLUMN "system_config_history"."change_type" IS '变更类型：UPDATE、CREATE 或 DELETE';
COMMENT ON COLUMN "system_config_history"."created_at" IS '变更时间';

COMMENT ON TABLE "slash_commands" IS '调试快捷指令表';
COMMENT ON COLUMN "slash_commands"."id" IS '快捷指令主键 ID';
COMMENT ON COLUMN "slash_commands"."label" IS '前端显示名称';
COMMENT ON COLUMN "slash_commands"."command" IS '执行指令内容';
COMMENT ON COLUMN "slash_commands"."sort_order" IS '排序权重';
COMMENT ON COLUMN "slash_commands"."created_by" IS '创建人';
COMMENT ON COLUMN "slash_commands"."created_at" IS '创建时间';
COMMENT ON COLUMN "slash_commands"."updated_at" IS '最后更新时间';

COMMENT ON TABLE "memory_service_configs" IS '记忆管理中心服务配置表';
COMMENT ON COLUMN "memory_service_configs"."key" IS '记忆服务配置键名';
COMMENT ON COLUMN "memory_service_configs"."value" IS '记忆服务配置值';
COMMENT ON COLUMN "memory_service_configs"."description" IS '配置说明';
COMMENT ON COLUMN "memory_service_configs"."is_secret" IS '是否为敏感配置';
COMMENT ON COLUMN "memory_service_configs"."created_at" IS '创建时间';
COMMENT ON COLUMN "memory_service_configs"."updated_at" IS '最后更新时间';

COMMENT ON TABLE "ai_agents" IS '智能体定义表';
COMMENT ON COLUMN "ai_agents"."id" IS '智能体唯一 ID';
COMMENT ON COLUMN "ai_agents"."name" IS '智能体内部名称';
COMMENT ON COLUMN "ai_agents"."display_name" IS '智能体显示名称';
COMMENT ON COLUMN "ai_agents"."description" IS '智能体功能描述';
COMMENT ON COLUMN "ai_agents"."avatar_url" IS '智能体头像地址';
COMMENT ON COLUMN "ai_agents"."capabilities" IS '智能体能力标签 JSON';
COMMENT ON COLUMN "ai_agents"."agent_type" IS '面向用户的智能体类型';
COMMENT ON COLUMN "ai_agents"."onboarding_key" IS '新手引导标识';
COMMENT ON COLUMN "ai_agents"."onboarding_step" IS '当前新手引导步骤';
COMMENT ON COLUMN "ai_agents"."is_system" IS '是否为系统内置智能体';
COMMENT ON COLUMN "ai_agents"."sort_order" IS '智能体排序值';
COMMENT ON COLUMN "ai_agents"."is_enabled" IS '是否启用';
COMMENT ON COLUMN "ai_agents"."engine_type" IS '运行引擎类型';
COMMENT ON COLUMN "ai_agents"."engine_config" IS '运行引擎配置 JSON';
COMMENT ON COLUMN "ai_agents"."created_by" IS '创建者用户名';
COMMENT ON COLUMN "ai_agents"."owner_group" IS '所属用户组';
COMMENT ON COLUMN "ai_agents"."created_at" IS '创建时间';
COMMENT ON COLUMN "ai_agents"."updated_at" IS '最后更新时间';

COMMENT ON TABLE "ai_agent_versions" IS '智能体版本与提示词配置表';
COMMENT ON COLUMN "ai_agent_versions"."id" IS '版本唯一 ID';
COMMENT ON COLUMN "ai_agent_versions"."agent_id" IS '所属智能体 ID';
COMMENT ON COLUMN "ai_agent_versions"."version_number" IS '版本序号';
COMMENT ON COLUMN "ai_agent_versions"."model_name" IS '主模型名称';
COMMENT ON COLUMN "ai_agent_versions"."temperature" IS '主模型温度参数';
COMMENT ON COLUMN "ai_agent_versions"."synthesis_model_name" IS '合成模型名称';
COMMENT ON COLUMN "ai_agent_versions"."synthesis_temperature" IS '合成模型温度参数';
COMMENT ON COLUMN "ai_agent_versions"."system_prompt" IS '系统提示词';
COMMENT ON COLUMN "ai_agent_versions"."tools" IS '允许使用的工具列表 JSON';
COMMENT ON COLUMN "ai_agent_versions"."skills_custom" IS '是否自定义公共 Skills';
COMMENT ON COLUMN "ai_agent_versions"."skills" IS '自定义公共技能 ID 列表 JSON';
COMMENT ON COLUMN "ai_agent_versions"."welcome_config" IS '欢迎页三卡片配置 JSON';
COMMENT ON COLUMN "ai_agent_versions"."status" IS '版本状态：DRAFT、PUBLISHED 或 ARCHIVED';
COMMENT ON COLUMN "ai_agent_versions"."comment" IS '版本变更说明';
COMMENT ON COLUMN "ai_agent_versions"."created_at" IS '创建时间';

COMMENT ON TABLE "ai_models" IS '平台模型配置表';
COMMENT ON COLUMN "ai_models"."id" IS '模型配置唯一 ID';
COMMENT ON COLUMN "ai_models"."name" IS '模型显示名称';
COMMENT ON COLUMN "ai_models"."model_id" IS '供应商侧模型标识';
COMMENT ON COLUMN "ai_models"."provider" IS '模型供应商';
COMMENT ON COLUMN "ai_models"."type" IS '模型类型：llm 或 embedding';
COMMENT ON COLUMN "ai_models"."api_base_url" IS '模型 API 地址覆盖值';
COMMENT ON COLUMN "ai_models"."api_key" IS '模型 API Key';
COMMENT ON COLUMN "ai_models"."is_active" IS '是否启用';
COMMENT ON COLUMN "ai_models"."created_at" IS '创建时间';
COMMENT ON COLUMN "ai_models"."updated_at" IS '最后更新时间';

COMMENT ON TABLE "ai_agent_roles" IS '智能体平台角色表';
COMMENT ON COLUMN "ai_agent_roles"."id" IS '角色主键 ID';
COMMENT ON COLUMN "ai_agent_roles"."code" IS '角色编码';
COMMENT ON COLUMN "ai_agent_roles"."name" IS '角色名称';
COMMENT ON COLUMN "ai_agent_roles"."description" IS '角色说明';
COMMENT ON COLUMN "ai_agent_roles"."created_at" IS '创建时间';
COMMENT ON COLUMN "ai_agent_roles"."updated_at" IS '最后更新时间';

COMMENT ON TABLE "ai_agent_user_role_relations" IS '用户与角色关系表';
COMMENT ON COLUMN "ai_agent_user_role_relations"."id" IS '关系记录主键 ID';
COMMENT ON COLUMN "ai_agent_user_role_relations"."user_id" IS '用户 ID';
COMMENT ON COLUMN "ai_agent_user_role_relations"."role_id" IS '角色 ID';
COMMENT ON COLUMN "ai_agent_user_role_relations"."created_at" IS '关系创建时间';

COMMENT ON TABLE "ai_agent_resource_permissions" IS '智能体资源权限表';
COMMENT ON COLUMN "ai_agent_resource_permissions"."id" IS '权限记录主键 ID';
COMMENT ON COLUMN "ai_agent_resource_permissions"."user_id" IS '授权用户 ID';
COMMENT ON COLUMN "ai_agent_resource_permissions"."role_id" IS '授权角色 ID';
COMMENT ON COLUMN "ai_agent_resource_permissions"."resource_type" IS '资源类型：agent、dataset、menu 或 element';
COMMENT ON COLUMN "ai_agent_resource_permissions"."resource_id" IS '资源业务 ID';
COMMENT ON COLUMN "ai_agent_resource_permissions"."enabled" IS '是否启用该权限';
COMMENT ON COLUMN "ai_agent_resource_permissions"."created_at" IS '创建时间';
COMMENT ON COLUMN "ai_agent_resource_permissions"."updated_at" IS '最后更新时间';

COMMENT ON TABLE "meta_datasets" IS '业务数据集定义表';
COMMENT ON COLUMN "meta_datasets"."id" IS '数据集主键 ID';
COMMENT ON COLUMN "meta_datasets"."name" IS '数据集内部名称';
COMMENT ON COLUMN "meta_datasets"."display_name" IS '数据集显示名称';
COMMENT ON COLUMN "meta_datasets"."description" IS '数据集业务描述';
COMMENT ON COLUMN "meta_datasets"."tags" IS '数据集标签 JSON';
COMMENT ON COLUMN "meta_datasets"."data_source" IS '数据源类型：clickhouse、mysql、postgresql 等';
COMMENT ON COLUMN "meta_datasets"."status" IS '数据集状态：1 启用，0 停用';
COMMENT ON COLUMN "meta_datasets"."enable_data_perm" IS '是否启用精细化数据权限';
COMMENT ON COLUMN "meta_datasets"."row_filter_config" IS '行级权限过滤策略 JSON';
COMMENT ON COLUMN "meta_datasets"."rag_dataset_id" IS 'RAGFlow Dataset ID';
COMMENT ON COLUMN "meta_datasets"."rag_synced_at" IS '最后同步到 RAGFlow 的时间';
COMMENT ON COLUMN "meta_datasets"."rag_sync_status" IS 'RAGFlow 同步状态';
COMMENT ON COLUMN "meta_datasets"."rag_sync_notes" IS 'RAGFlow 同步日志或错误信息';
COMMENT ON COLUMN "meta_datasets"."created_at" IS '创建时间';
COMMENT ON COLUMN "meta_datasets"."updated_at" IS '最后更新时间';

COMMENT ON TABLE "meta_tables" IS '数据集物理表元数据定义表';
COMMENT ON COLUMN "meta_tables"."id" IS '物理表元数据主键 ID';
COMMENT ON COLUMN "meta_tables"."dataset_id" IS '所属数据集 ID';
COMMENT ON COLUMN "meta_tables"."physical_name" IS '物理表名';
COMMENT ON COLUMN "meta_tables"."term" IS '表的业务术语';
COMMENT ON COLUMN "meta_tables"."description" IS '表的业务描述';
COMMENT ON COLUMN "meta_tables"."synonyms" IS '表的同义词列表 JSON';
COMMENT ON COLUMN "meta_tables"."status" IS '表状态：1 启用，0 停用';
COMMENT ON COLUMN "meta_tables"."created_at" IS '创建时间';
COMMENT ON COLUMN "meta_tables"."updated_at" IS '最后更新时间';

COMMENT ON TABLE "meta_columns" IS '物理表字段元数据定义表';
COMMENT ON COLUMN "meta_columns"."id" IS '字段元数据主键 ID';
COMMENT ON COLUMN "meta_columns"."table_id" IS '所属物理表 ID';
COMMENT ON COLUMN "meta_columns"."physical_name" IS '物理字段名';
COMMENT ON COLUMN "meta_columns"."term" IS '字段业务术语';
COMMENT ON COLUMN "meta_columns"."type" IS '字段业务或数据库类型';
COMMENT ON COLUMN "meta_columns"."description" IS '字段业务描述';
COMMENT ON COLUMN "meta_columns"."enums" IS '枚举值定义 JSON';
COMMENT ON COLUMN "meta_columns"."synonyms" IS '字段同义词列表 JSON';
COMMENT ON COLUMN "meta_columns"."examples" IS '字段示例值列表 JSON';
COMMENT ON COLUMN "meta_columns"."foreign_key" IS '外键关联描述';
COMMENT ON COLUMN "meta_columns"."is_primary" IS '是否为业务主键字段';
COMMENT ON COLUMN "meta_columns"."created_at" IS '创建时间';

COMMENT ON TABLE "meta_metrics" IS '业务指标定义表';
COMMENT ON COLUMN "meta_metrics"."id" IS '指标主键 ID';
COMMENT ON COLUMN "meta_metrics"."dataset_id" IS '所属数据集 ID';
COMMENT ON COLUMN "meta_metrics"."name" IS '指标内部名称';
COMMENT ON COLUMN "meta_metrics"."display_name" IS '指标显示名称';
COMMENT ON COLUMN "meta_metrics"."description" IS '业务口径描述';
COMMENT ON COLUMN "meta_metrics"."calculation_logic" IS '指标计算逻辑或公式';
COMMENT ON COLUMN "meta_metrics"."unit" IS '指标单位';
COMMENT ON COLUMN "meta_metrics"."created_at" IS '创建时间';
COMMENT ON COLUMN "meta_metrics"."updated_at" IS '最后更新时间';

COMMENT ON TABLE "meta_relationships" IS '元数据表间关系定义表';
COMMENT ON COLUMN "meta_relationships"."id" IS '关系主键 ID';
COMMENT ON COLUMN "meta_relationships"."source_table_id" IS '源表 ID';
COMMENT ON COLUMN "meta_relationships"."target_table_id" IS '目标表 ID';
COMMENT ON COLUMN "meta_relationships"."join_condition" IS '表关联条件';
COMMENT ON COLUMN "meta_relationships"."join_type" IS '关联类型：LEFT、INNER 或 RIGHT';
COMMENT ON COLUMN "meta_relationships"."description" IS '关系业务描述';

COMMENT ON TABLE "meta_changelog" IS '元数据变更日志表';
COMMENT ON COLUMN "meta_changelog"."id" IS '变更日志主键 ID';
COMMENT ON COLUMN "meta_changelog"."resource_type" IS '资源类型：dataset、table、column、metric 或 relationship';
COMMENT ON COLUMN "meta_changelog"."resource_id" IS '资源业务 ID';
COMMENT ON COLUMN "meta_changelog"."operation" IS '操作类型：create、update 或 delete';
COMMENT ON COLUMN "meta_changelog"."old_data" IS '变更前数据 JSON';
COMMENT ON COLUMN "meta_changelog"."new_data" IS '变更后数据 JSON';
COMMENT ON COLUMN "meta_changelog"."changed_fields" IS '变更字段列表 JSON';
COMMENT ON COLUMN "meta_changelog"."user_id" IS '操作用户 ID';
COMMENT ON COLUMN "meta_changelog"."user_name" IS '操作用户名';
COMMENT ON COLUMN "meta_changelog"."reason" IS '变更原因';
COMMENT ON COLUMN "meta_changelog"."created_at" IS '变更时间';

COMMENT ON TABLE "meta_db_connection_configs" IS '外部数据源连接配置表';
COMMENT ON COLUMN "meta_db_connection_configs"."id" IS '连接配置主键 ID';
COMMENT ON COLUMN "meta_db_connection_configs"."name" IS '连接别名';
COMMENT ON COLUMN "meta_db_connection_configs"."db_type" IS '外部数据库类型';
COMMENT ON COLUMN "meta_db_connection_configs"."host" IS '外部数据库主机地址';
COMMENT ON COLUMN "meta_db_connection_configs"."port" IS '外部数据库端口';
COMMENT ON COLUMN "meta_db_connection_configs"."db_user" IS '外部数据库用户名';
COMMENT ON COLUMN "meta_db_connection_configs"."password" IS '外部数据库密码';
COMMENT ON COLUMN "meta_db_connection_configs"."database_name" IS '外部数据库名称';
COMMENT ON COLUMN "meta_db_connection_configs"."description" IS '数据源用途说明';
COMMENT ON COLUMN "meta_db_connection_configs"."created_by" IS '创建用户 ID';
COMMENT ON COLUMN "meta_db_connection_configs"."created_at" IS '创建时间';
COMMENT ON COLUMN "meta_db_connection_configs"."updated_at" IS '最后更新时间';

COMMENT ON TABLE "db_profile_tasks" IS '外部数据源摸排任务表';
COMMENT ON COLUMN "db_profile_tasks"."id" IS '摸排任务主键 ID';
COMMENT ON COLUMN "db_profile_tasks"."connection_id" IS '外部数据源连接配置 ID';
COMMENT ON COLUMN "db_profile_tasks"."status" IS '任务状态：0 排队，1 进行中，2 完成，3 异常';
COMMENT ON COLUMN "db_profile_tasks"."total_tables" IS '待处理表或视图总数';
COMMENT ON COLUMN "db_profile_tasks"."processed_tables" IS '已处理表或视图数量';
COMMENT ON COLUMN "db_profile_tasks"."current_table" IS '当前正在处理的物理表名';
COMMENT ON COLUMN "db_profile_tasks"."error_message" IS '任务异常说明';
COMMENT ON COLUMN "db_profile_tasks"."created_at" IS '创建时间';
COMMENT ON COLUMN "db_profile_tasks"."updated_at" IS '最后更新时间';

COMMENT ON TABLE "db_table_profiles" IS '外部数据源表与视图画像草稿表';
COMMENT ON COLUMN "db_table_profiles"."id" IS '表画像主键 ID';
COMMENT ON COLUMN "db_table_profiles"."connection_id" IS '外部数据源连接配置 ID';
COMMENT ON COLUMN "db_table_profiles"."table_name" IS '数据库物理表或视图名';
COMMENT ON COLUMN "db_table_profiles"."table_type" IS '对象类型：table 或 view';
COMMENT ON COLUMN "db_table_profiles"."engine" IS '外部对象存储引擎';
COMMENT ON COLUMN "db_table_profiles"."ddl" IS '物理建表 DDL';
COMMENT ON COLUMN "db_table_profiles"."sample_data" IS '采样数据 JSON 文本';
COMMENT ON COLUMN "db_table_profiles"."ai_term" IS 'AI 识别的业务术语';
COMMENT ON COLUMN "db_table_profiles"."ai_description" IS 'AI 生成的业务用途描述';
COMMENT ON COLUMN "db_table_profiles"."ai_tags" IS 'AI 生成的分类标签 JSON';
COMMENT ON COLUMN "db_table_profiles"."columns_profile" IS 'AI 生成的字段画像 JSON';
COMMENT ON COLUMN "db_table_profiles"."status" IS '摸排状态：0 待开始，1 进行中，2 成功，3 失败';
COMMENT ON COLUMN "db_table_profiles"."confidence_score" IS '业务相关度置信度评分，范围 0 到 100';
COMMENT ON COLUMN "db_table_profiles"."is_temporary" IS '是否为临时或备份表';
COMMENT ON COLUMN "db_table_profiles"."is_ignored" IS '分析时是否忽略该表';
COMMENT ON COLUMN "db_table_profiles"."confidence_reason" IS '置信度判定与扣分原因';
COMMENT ON COLUMN "db_table_profiles"."error_message" IS '画像分析失败说明';
COMMENT ON COLUMN "db_table_profiles"."created_at" IS '创建时间';
COMMENT ON COLUMN "db_table_profiles"."updated_at" IS '最后更新时间';

COMMENT ON TABLE "ai_agent_execution_traces" IS '智能体执行链路步骤日志表';
COMMENT ON COLUMN "ai_agent_execution_traces"."id" IS '执行步骤主键 ID';
COMMENT ON COLUMN "ai_agent_execution_traces"."trace_id" IS '关联会话链路 ID';
COMMENT ON COLUMN "ai_agent_execution_traces"."step_number" IS '链路步骤序号';
COMMENT ON COLUMN "ai_agent_execution_traces"."event_type" IS '事件类型：thought、tool_call、tool_result 或 final_answer';
COMMENT ON COLUMN "ai_agent_execution_traces"."agent_name" IS '执行步骤的智能体名称';
COMMENT ON COLUMN "ai_agent_execution_traces"."tool_name" IS '调用的工具名称';
COMMENT ON COLUMN "ai_agent_execution_traces"."tool_input" IS '工具输入参数 JSON';
COMMENT ON COLUMN "ai_agent_execution_traces"."tool_output" IS '工具输出结果 JSON';
COMMENT ON COLUMN "ai_agent_execution_traces"."execution_time_ms" IS '步骤耗时，单位毫秒';
COMMENT ON COLUMN "ai_agent_execution_traces"."status" IS '步骤执行状态';
COMMENT ON COLUMN "ai_agent_execution_traces"."error_message" IS '步骤错误详情';
COMMENT ON COLUMN "ai_agent_execution_traces"."model" IS '实际使用的模型名称';
COMMENT ON COLUMN "ai_agent_execution_traces"."temperature" IS '模型温度参数';
COMMENT ON COLUMN "ai_agent_execution_traces"."prompt_tokens" IS '输入 Token 消耗数';
COMMENT ON COLUMN "ai_agent_execution_traces"."completion_tokens" IS '输出 Token 消耗数';
COMMENT ON COLUMN "ai_agent_execution_traces"."total_tokens" IS '总 Token 消耗数';
COMMENT ON COLUMN "ai_agent_execution_traces"."span_id" IS '当前 Span 唯一标识';
COMMENT ON COLUMN "ai_agent_execution_traces"."parent_span_id" IS '父级 Span 唯一标识';
COMMENT ON COLUMN "ai_agent_execution_traces"."meta_info" IS '步骤额外元数据 JSON';
COMMENT ON COLUMN "ai_agent_execution_traces"."created_at" IS '步骤创建时间';

COMMENT ON TABLE "ai_agent_execution_history" IS '智能体对话执行历史表';
COMMENT ON COLUMN "ai_agent_execution_history"."id" IS '执行历史主键 ID';
COMMENT ON COLUMN "ai_agent_execution_history"."agent_id" IS '智能体 ID';
COMMENT ON COLUMN "ai_agent_execution_history"."trace_id" IS '关联链路 ID';
COMMENT ON COLUMN "ai_agent_execution_history"."conversation_id" IS '会话 ID';
COMMENT ON COLUMN "ai_agent_execution_history"."user_id" IS '提问用户 ID';
COMMENT ON COLUMN "ai_agent_execution_history"."username" IS '提问用户名';
COMMENT ON COLUMN "ai_agent_execution_history"."query" IS '用户提问内容';
COMMENT ON COLUMN "ai_agent_execution_history"."summary" IS '智能体响应摘要';
COMMENT ON COLUMN "ai_agent_execution_history"."prompt_tokens" IS '输入 Token 消耗数';
COMMENT ON COLUMN "ai_agent_execution_history"."completion_tokens" IS '输出 Token 消耗数';
COMMENT ON COLUMN "ai_agent_execution_history"."total_tokens" IS '总 Token 消耗数';
COMMENT ON COLUMN "ai_agent_execution_history"."execution_time_ms" IS '本次执行耗时，单位毫秒';
COMMENT ON COLUMN "ai_agent_execution_history"."status" IS '执行状态：success 或 failed';
COMMENT ON COLUMN "ai_agent_execution_history"."agent_version" IS '生成响应的智能体版本号';
COMMENT ON COLUMN "ai_agent_execution_history"."model_id" IS '实际使用的模型标识快照';
COMMENT ON COLUMN "ai_agent_execution_history"."model_config_id" IS '使用的模型配置 ID';
COMMENT ON COLUMN "ai_agent_execution_history"."feedback" IS '用户反馈：up 或 down';
COMMENT ON COLUMN "ai_agent_execution_history"."created_at" IS '执行时间';

COMMENT ON TABLE "ai_agent_access_logs" IS '平台 API 访问日志表';
COMMENT ON COLUMN "ai_agent_access_logs"."id" IS '访问日志主键 ID';
COMMENT ON COLUMN "ai_agent_access_logs"."trace_id" IS '请求链路 ID';
COMMENT ON COLUMN "ai_agent_access_logs"."user_id" IS '访问用户 ID';
COMMENT ON COLUMN "ai_agent_access_logs"."user_name" IS '访问用户名';
COMMENT ON COLUMN "ai_agent_access_logs"."feature_name" IS '功能点或菜单名称';
COMMENT ON COLUMN "ai_agent_access_logs"."endpoint" IS '请求接口地址';
COMMENT ON COLUMN "ai_agent_access_logs"."method" IS 'HTTP 请求方法';
COMMENT ON COLUMN "ai_agent_access_logs"."query_params" IS 'URL 查询参数';
COMMENT ON COLUMN "ai_agent_access_logs"."status_code" IS 'HTTP 响应状态码';
COMMENT ON COLUMN "ai_agent_access_logs"."process_time_ms" IS '请求处理耗时，单位毫秒';
COMMENT ON COLUMN "ai_agent_access_logs"."client_ip" IS '客户端 IP 地址';
COMMENT ON COLUMN "ai_agent_access_logs"."request_params" IS '请求参数 JSON 文本';
COMMENT ON COLUMN "ai_agent_access_logs"."response_body" IS '响应内容 JSON 文本';
COMMENT ON COLUMN "ai_agent_access_logs"."error_message" IS '请求错误信息';
COMMENT ON COLUMN "ai_agent_access_logs"."user_agent" IS '客户端 User-Agent';
COMMENT ON COLUMN "ai_agent_access_logs"."created_at" IS '访问时间';

COMMENT ON TABLE "ai_agent_scheduler_jobs" IS 'APScheduler 持久化任务存储表';
COMMENT ON COLUMN "ai_agent_scheduler_jobs"."id" IS '调度任务唯一 ID';
COMMENT ON COLUMN "ai_agent_scheduler_jobs"."next_run_time" IS '下一次运行时间戳';
COMMENT ON COLUMN "ai_agent_scheduler_jobs"."job_state" IS '调度任务序列化状态二进制数据';

COMMENT ON TABLE "ai_agent_scheduled_tasks" IS '智能体定时任务定义表';
COMMENT ON COLUMN "ai_agent_scheduled_tasks"."id" IS '定时任务主键 ID';
COMMENT ON COLUMN "ai_agent_scheduled_tasks"."name" IS '任务显示名称';
COMMENT ON COLUMN "ai_agent_scheduled_tasks"."user_id" IS '任务创建者 ID';
COMMENT ON COLUMN "ai_agent_scheduled_tasks"."agent_id" IS '绑定的智能体 ID';
COMMENT ON COLUMN "ai_agent_scheduled_tasks"."conversation_id" IS '执行结果写入的会话 ID';
COMMENT ON COLUMN "ai_agent_scheduled_tasks"."cron_expr" IS 'Cron 调度表达式';
COMMENT ON COLUMN "ai_agent_scheduled_tasks"."prompt" IS '定时执行时发送给智能体的指令';
COMMENT ON COLUMN "ai_agent_scheduled_tasks"."source" IS '任务来源：web 或 agent';
COMMENT ON COLUMN "ai_agent_scheduled_tasks"."status" IS '任务状态：0 停止，1 运行，2 异常';
COMMENT ON COLUMN "ai_agent_scheduled_tasks"."config" IS '通知、重试等额外配置 JSON';
COMMENT ON COLUMN "ai_agent_scheduled_tasks"."run_count" IS '累计执行次数';
COMMENT ON COLUMN "ai_agent_scheduled_tasks"."last_run_id" IS '最近一次运行链路 ID';
COMMENT ON COLUMN "ai_agent_scheduled_tasks"."last_run_at" IS '上次执行时间';
COMMENT ON COLUMN "ai_agent_scheduled_tasks"."next_run_at" IS '下次预计执行时间';
COMMENT ON COLUMN "ai_agent_scheduled_tasks"."created_at" IS '创建时间';
COMMENT ON COLUMN "ai_agent_scheduled_tasks"."updated_at" IS '最后更新时间';

COMMENT ON TABLE "sys_api_tools" IS '平台 API 工具注册表';
COMMENT ON COLUMN "sys_api_tools"."id" IS '工具唯一 ID';
COMMENT ON COLUMN "sys_api_tools"."name" IS '工具名称';
COMMENT ON COLUMN "sys_api_tools"."description" IS '工具功能描述';
COMMENT ON COLUMN "sys_api_tools"."method" IS 'HTTP 请求方法';
COMMENT ON COLUMN "sys_api_tools"."url_template" IS '目标 API URL 模板';
COMMENT ON COLUMN "sys_api_tools"."headers" IS '请求头 JSON 文本';
COMMENT ON COLUMN "sys_api_tools"."parameter_schema" IS '工具参数 Schema JSON 文本';
COMMENT ON COLUMN "sys_api_tools"."is_active" IS '是否启用';
COMMENT ON COLUMN "sys_api_tools"."created_at" IS '创建时间';
COMMENT ON COLUMN "sys_api_tools"."updated_at" IS '最后更新时间';

COMMENT ON TABLE "sys_mcp_servers" IS 'MCP 服务端注册表';
COMMENT ON COLUMN "sys_mcp_servers"."id" IS 'MCP 服务端唯一 ID';
COMMENT ON COLUMN "sys_mcp_servers"."server_name" IS 'MCP 服务端名称';
COMMENT ON COLUMN "sys_mcp_servers"."sse_url" IS 'MCP SSE 握手地址';
COMMENT ON COLUMN "sys_mcp_servers"."auth_headers" IS '认证请求头 JSON 文本';
COMMENT ON COLUMN "sys_mcp_servers"."enabled_status" IS '启用状态：0 禁用，1 启用';
COMMENT ON COLUMN "sys_mcp_servers"."last_sync_at" IS '最近一次工具同步时间';
COMMENT ON COLUMN "sys_mcp_servers"."created_at" IS '创建时间';
COMMENT ON COLUMN "sys_mcp_servers"."updated_at" IS '最后更新时间';

COMMENT ON TABLE "sys_mcp_tool_cache" IS 'MCP 工具发现缓存表';
COMMENT ON COLUMN "sys_mcp_tool_cache"."id" IS 'MCP 工具缓存唯一 ID';
COMMENT ON COLUMN "sys_mcp_tool_cache"."server_id" IS '所属 MCP 服务端 ID';
COMMENT ON COLUMN "sys_mcp_tool_cache"."tool_name" IS '工具完整名称';
COMMENT ON COLUMN "sys_mcp_tool_cache"."tool_description" IS '工具描述';
COMMENT ON COLUMN "sys_mcp_tool_cache"."parameter_schema" IS '工具参数 Schema JSON 文本';
COMMENT ON COLUMN "sys_mcp_tool_cache"."is_published" IS '是否发布给智能体使用';
COMMENT ON COLUMN "sys_mcp_tool_cache"."created_at" IS '创建时间';
COMMENT ON COLUMN "sys_mcp_tool_cache"."updated_at" IS '最后更新时间';

COMMENT ON TABLE "ai_chatbi_examples" IS 'ChatBI 优质问答与 SQL 经验案例表';
COMMENT ON COLUMN "ai_chatbi_examples"."id" IS '案例主键 ID';
COMMENT ON COLUMN "ai_chatbi_examples"."trace_id" IS '关联执行链路 ID';
COMMENT ON COLUMN "ai_chatbi_examples"."agent_id" IS '智能体 ID';
COMMENT ON COLUMN "ai_chatbi_examples"."dataset_id" IS '数据集 ID';
COMMENT ON COLUMN "ai_chatbi_examples"."user_query" IS '用户原始问题';
COMMENT ON COLUMN "ai_chatbi_examples"."refined_query" IS '增强后的完整问题';
COMMENT ON COLUMN "ai_chatbi_examples"."context_summary" IS '问题上下文摘要';
COMMENT ON COLUMN "ai_chatbi_examples"."sql_text" IS '成功执行的 SQL';
COMMENT ON COLUMN "ai_chatbi_examples"."sql_metadata" IS 'SQL 特征元数据 JSON';
COMMENT ON COLUMN "ai_chatbi_examples"."enhance_status" IS '案例增强状态';
COMMENT ON COLUMN "ai_chatbi_examples"."ai_answer" IS '智能体回答摘要';
COMMENT ON COLUMN "ai_chatbi_examples"."feedback_type" IS '反馈类型：up 或 down';
COMMENT ON COLUMN "ai_chatbi_examples"."status" IS '案例审核状态';
COMMENT ON COLUMN "ai_chatbi_examples"."error_message" IS '负向案例错误信息';
COMMENT ON COLUMN "ai_chatbi_examples"."use_count" IS '案例被引用次数';
COMMENT ON COLUMN "ai_chatbi_examples"."rag_doc_id" IS 'RAGFlow 文档 ID';
COMMENT ON COLUMN "ai_chatbi_examples"."rag_sync_status" IS 'RAGFlow 同步状态';
COMMENT ON COLUMN "ai_chatbi_examples"."rag_sync_error" IS 'RAGFlow 同步错误信息';
COMMENT ON COLUMN "ai_chatbi_examples"."rag_synced_at" IS '最后同步到 RAGFlow 的时间';
COMMENT ON COLUMN "ai_chatbi_examples"."user_id" IS '反馈用户 ID';
COMMENT ON COLUMN "ai_chatbi_examples"."created_at" IS '创建时间';
COMMENT ON COLUMN "ai_chatbi_examples"."updated_at" IS '最后更新时间';

COMMENT ON TABLE "ai_chatbi_example_usages" IS 'ChatBI 经验案例引用流水表';
COMMENT ON COLUMN "ai_chatbi_example_usages"."id" IS '引用记录主键 ID';
COMMENT ON COLUMN "ai_chatbi_example_usages"."example_id" IS '被引用案例 ID';
COMMENT ON COLUMN "ai_chatbi_example_usages"."trace_id" IS '当前对话链路 ID';
COMMENT ON COLUMN "ai_chatbi_example_usages"."similarity" IS '检索相似度';
COMMENT ON COLUMN "ai_chatbi_example_usages"."created_at" IS '引用时间';

COMMENT ON TABLE "portal_saved_reports" IS 'ChatBI 已保存黄金报表表';
COMMENT ON COLUMN "portal_saved_reports"."id" IS '保存报表唯一 ID';
COMMENT ON COLUMN "portal_saved_reports"."title" IS '报表标题';
COMMENT ON COLUMN "portal_saved_reports"."description" IS '报表说明';
COMMENT ON COLUMN "portal_saved_reports"."sql_content" IS '报表执行 SQL';
COMMENT ON COLUMN "portal_saved_reports"."dataset_id" IS '关联数据集 ID';
COMMENT ON COLUMN "portal_saved_reports"."data_source" IS '报表使用的数据源';
COMMENT ON COLUMN "portal_saved_reports"."original_query" IS '生成报表的原始问题';
COMMENT ON COLUMN "portal_saved_reports"."mode" IS '报表 SQL 模式';
COMMENT ON COLUMN "portal_saved_reports"."sql_template" IS '参数化 SQL 模板';
COMMENT ON COLUMN "portal_saved_reports"."params_schema" IS '参数定义 Schema JSON';
COMMENT ON COLUMN "portal_saved_reports"."default_params" IS '默认参数 JSON';
COMMENT ON COLUMN "portal_saved_reports"."analysis_mode" IS '分析模式';
COMMENT ON COLUMN "portal_saved_reports"."tags" IS '报表标签 JSON';
COMMENT ON COLUMN "portal_saved_reports"."owner_user_id" IS '报表所有者用户 ID';
COMMENT ON COLUMN "portal_saved_reports"."owner_name" IS '报表所有者名称快照';
COMMENT ON COLUMN "portal_saved_reports"."visibility" IS '可见范围';
COMMENT ON COLUMN "portal_saved_reports"."status" IS '报表状态';
COMMENT ON COLUMN "portal_saved_reports"."last_run_at" IS '最近运行时间';
COMMENT ON COLUMN "portal_saved_reports"."last_success_at" IS '最近成功运行时间';
COMMENT ON COLUMN "portal_saved_reports"."last_error" IS '最近一次运行错误';
COMMENT ON COLUMN "portal_saved_reports"."created_at" IS '创建时间';
COMMENT ON COLUMN "portal_saved_reports"."updated_at" IS '最后更新时间';

COMMENT ON TABLE "portal_saved_report_shares" IS '已保存报表共享对象表';
COMMENT ON COLUMN "portal_saved_report_shares"."id" IS '共享记录主键 ID';
COMMENT ON COLUMN "portal_saved_report_shares"."report_id" IS '已保存报表 ID';
COMMENT ON COLUMN "portal_saved_report_shares"."target_type" IS '共享对象类型';
COMMENT ON COLUMN "portal_saved_report_shares"."target_id" IS '共享对象业务 ID';
COMMENT ON COLUMN "portal_saved_report_shares"."permission" IS '共享权限';
COMMENT ON COLUMN "portal_saved_report_shares"."created_by" IS '共享创建者用户 ID';
COMMENT ON COLUMN "portal_saved_report_shares"."created_at" IS '创建时间';

COMMENT ON TABLE "portal_saved_report_user_prefs" IS '用户已保存报表偏好表';
COMMENT ON COLUMN "portal_saved_report_user_prefs"."id" IS '偏好记录主键 ID';
COMMENT ON COLUMN "portal_saved_report_user_prefs"."report_id" IS '已保存报表 ID';
COMMENT ON COLUMN "portal_saved_report_user_prefs"."user_id" IS '用户 ID';
COMMENT ON COLUMN "portal_saved_report_user_prefs"."is_favorite" IS '是否收藏';
COMMENT ON COLUMN "portal_saved_report_user_prefs"."pinned_at" IS '置顶时间';
COMMENT ON COLUMN "portal_saved_report_user_prefs"."last_viewed_at" IS '最近浏览时间';
COMMENT ON COLUMN "portal_saved_report_user_prefs"."run_count" IS '用户运行次数';
COMMENT ON COLUMN "portal_saved_report_user_prefs"."last_run_at" IS '最近运行时间';
COMMENT ON COLUMN "portal_saved_report_user_prefs"."created_at" IS '创建时间';
COMMENT ON COLUMN "portal_saved_report_user_prefs"."updated_at" IS '最后更新时间';

COMMENT ON TABLE "portal_saved_report_runs" IS '已保存报表运行历史与结果快照表';
COMMENT ON COLUMN "portal_saved_report_runs"."id" IS '运行记录主键 ID';
COMMENT ON COLUMN "portal_saved_report_runs"."report_id" IS '已保存报表 ID';
COMMENT ON COLUMN "portal_saved_report_runs"."user_id" IS '本次运行用户 ID';
COMMENT ON COLUMN "portal_saved_report_runs"."trigger_type" IS '触发类型：manual 或 scheduled';
COMMENT ON COLUMN "portal_saved_report_runs"."task_id" IS '关联定时任务 ID';
COMMENT ON COLUMN "portal_saved_report_runs"."status" IS '运行状态';
COMMENT ON COLUMN "portal_saved_report_runs"."resolved_params" IS '解析后的运行参数 JSON';
COMMENT ON COLUMN "portal_saved_report_runs"."executed_sql" IS '本次实际执行的 SQL';
COMMENT ON COLUMN "portal_saved_report_runs"."data_source" IS '本次运行使用的数据源';
COMMENT ON COLUMN "portal_saved_report_runs"."dataset_name" IS '本次运行使用的数据集名称';
COMMENT ON COLUMN "portal_saved_report_runs"."row_count" IS '查询结果总行数';
COMMENT ON COLUMN "portal_saved_report_runs"."snapshot_row_count" IS '实际保存的结果快照行数';
COMMENT ON COLUMN "portal_saved_report_runs"."result_snapshot" IS '结果快照 JSON';
COMMENT ON COLUMN "portal_saved_report_runs"."permission_notice" IS '数据权限处理摘要 JSON';
COMMENT ON COLUMN "portal_saved_report_runs"."duration_ms" IS '运行耗时，单位毫秒';
COMMENT ON COLUMN "portal_saved_report_runs"."error_message" IS '面向用户的运行错误说明';
COMMENT ON COLUMN "portal_saved_report_runs"."started_at" IS '运行开始时间';
COMMENT ON COLUMN "portal_saved_report_runs"."finished_at" IS '运行完成或失败时间';

COMMENT ON TABLE "portal_saved_report_subscriptions" IS '黄金报表定时订阅配置表';
COMMENT ON COLUMN "portal_saved_report_subscriptions"."id" IS '订阅主键 ID';
COMMENT ON COLUMN "portal_saved_report_subscriptions"."report_id" IS '黄金报表 ID';
COMMENT ON COLUMN "portal_saved_report_subscriptions"."user_id" IS '订阅创建人与执行用户 ID';
COMMENT ON COLUMN "portal_saved_report_subscriptions"."schedule_type" IS '频率类型：daily、weekly、monthly 或 cron';
COMMENT ON COLUMN "portal_saved_report_subscriptions"."cron_expr" IS '标准 Cron 表达式';
COMMENT ON COLUMN "portal_saved_report_subscriptions"."timezone" IS '调度时区';
COMMENT ON COLUMN "portal_saved_report_subscriptions"."params" IS '定时运行报表参数 JSON';
COMMENT ON COLUMN "portal_saved_report_subscriptions"."ai_analysis_enabled" IS '是否启用 AI 智能分析';
COMMENT ON COLUMN "portal_saved_report_subscriptions"."analysis_instruction" IS '订阅级 AI 分析要求';
COMMENT ON COLUMN "portal_saved_report_subscriptions"."notify_on_success" IS '成功时是否生成通知';
COMMENT ON COLUMN "portal_saved_report_subscriptions"."notify_on_failure" IS '失败时是否生成通知';
COMMENT ON COLUMN "portal_saved_report_subscriptions"."external_channels" IS '外部通知渠道 JSON';
COMMENT ON COLUMN "portal_saved_report_subscriptions"."alert_condition" IS '版本化告警条件 JSON';
COMMENT ON COLUMN "portal_saved_report_subscriptions"."alert_state" IS '最近告警基线与命中状态 JSON';
COMMENT ON COLUMN "portal_saved_report_subscriptions"."status" IS '订阅状态';
COMMENT ON COLUMN "portal_saved_report_subscriptions"."consecutive_failures" IS '连续失败次数';
COMMENT ON COLUMN "portal_saved_report_subscriptions"."last_run_id" IS '最近一次运行记录 ID';
COMMENT ON COLUMN "portal_saved_report_subscriptions"."last_run_at" IS '最近一次运行时间';
COMMENT ON COLUMN "portal_saved_report_subscriptions"."next_run_at" IS '下一次计划运行时间';
COMMENT ON COLUMN "portal_saved_report_subscriptions"."last_error" IS '最近一次错误信息';
COMMENT ON COLUMN "portal_saved_report_subscriptions"."created_at" IS '创建时间';
COMMENT ON COLUMN "portal_saved_report_subscriptions"."updated_at" IS '最后更新时间';

COMMENT ON TABLE "portal_saved_report_digest_deliveries" IS '黄金报表智能简报推送审计表';
COMMENT ON COLUMN "portal_saved_report_digest_deliveries"."id" IS '推送审计主键 ID';
COMMENT ON COLUMN "portal_saved_report_digest_deliveries"."run_id" IS '报表运行记录 ID';
COMMENT ON COLUMN "portal_saved_report_digest_deliveries"."subscription_id" IS '报表订阅 ID';
COMMENT ON COLUMN "portal_saved_report_digest_deliveries"."channel" IS '推送渠道：inbox、dingtalk、wechat_work 或 email';
COMMENT ON COLUMN "portal_saved_report_digest_deliveries"."digest_payload" IS '结构化智能简报 JSON';
COMMENT ON COLUMN "portal_saved_report_digest_deliveries"."trigger_evidence" IS '告警判断与触发证据 JSON';
COMMENT ON COLUMN "portal_saved_report_digest_deliveries"."title" IS '实际发送的消息标题';
COMMENT ON COLUMN "portal_saved_report_digest_deliveries"."content" IS '实际发送的消息正文';
COMMENT ON COLUMN "portal_saved_report_digest_deliveries"."status" IS '发送状态：pending、success 或 failed';
COMMENT ON COLUMN "portal_saved_report_digest_deliveries"."error_message" IS '渠道发送失败原因';
COMMENT ON COLUMN "portal_saved_report_digest_deliveries"."ai_status" IS 'AI 生成状态';
COMMENT ON COLUMN "portal_saved_report_digest_deliveries"."sent_at" IS '发送完成时间';
COMMENT ON COLUMN "portal_saved_report_digest_deliveries"."created_at" IS '审计记录创建时间';

COMMENT ON TABLE "portal_notifications" IS '用户站内通知表';
COMMENT ON COLUMN "portal_notifications"."id" IS '通知主键 ID';
COMMENT ON COLUMN "portal_notifications"."user_id" IS '通知接收用户 ID';
COMMENT ON COLUMN "portal_notifications"."category" IS '通知业务分类';
COMMENT ON COLUMN "portal_notifications"."level" IS '通知等级：success、warning、error 或 info';
COMMENT ON COLUMN "portal_notifications"."title" IS '通知标题';
COMMENT ON COLUMN "portal_notifications"."content" IS '通知摘要内容';
COMMENT ON COLUMN "portal_notifications"."resource_type" IS '关联资源类型';
COMMENT ON COLUMN "portal_notifications"."resource_id" IS '关联资源 ID';
COMMENT ON COLUMN "portal_notifications"."metadata" IS '通知跳转和展示摘要 JSON';
COMMENT ON COLUMN "portal_notifications"."read_at" IS '已读时间，为空表示未读';
COMMENT ON COLUMN "portal_notifications"."created_at" IS '通知创建时间';

COMMENT ON TABLE "chatbi_briefs" IS 'ChatBI 证据化业务简报表';
COMMENT ON COLUMN "chatbi_briefs"."id" IS '业务简报唯一 ID';
COMMENT ON COLUMN "chatbi_briefs"."owner_user_id" IS '简报所属用户 ID';
COMMENT ON COLUMN "chatbi_briefs"."conversation_id" IS '来源 ChatBI 会话 ID';
COMMENT ON COLUMN "chatbi_briefs"."result_id" IS '来源结构化结果 ID';
COMMENT ON COLUMN "chatbi_briefs"."title" IS '业务简报标题';
COMMENT ON COLUMN "chatbi_briefs"."brief_payload" IS '简报结构化内容与证据 JSON';
COMMENT ON COLUMN "chatbi_briefs"."markdown_content" IS '简报 Markdown 正文';
COMMENT ON COLUMN "chatbi_briefs"."artifact_payload" IS '生成文件下载信息 JSON';
COMMENT ON COLUMN "chatbi_briefs"."created_at" IS '简报创建时间';

COMMENT ON TABLE "knowledge_base_metadata" IS '平台侧知识库扩展元数据表';
COMMENT ON COLUMN "knowledge_base_metadata"."id" IS '知识库元数据主键 ID';
COMMENT ON COLUMN "knowledge_base_metadata"."ragflow_dataset_id" IS 'RAGFlow Dataset ID';
COMMENT ON COLUMN "knowledge_base_metadata"."name" IS '知识库名称快照';
COMMENT ON COLUMN "knowledge_base_metadata"."description" IS '知识库描述快照';
COMMENT ON COLUMN "knowledge_base_metadata"."owner" IS '业务归属或负责人';
COMMENT ON COLUMN "knowledge_base_metadata"."visibility" IS '可见性：private、team 或 public';
COMMENT ON COLUMN "knowledge_base_metadata"."tags" IS '平台侧标签 JSON';
COMMENT ON COLUMN "knowledge_base_metadata"."notes" IS '平台侧备注';
COMMENT ON COLUMN "knowledge_base_metadata"."extra_config" IS '知识库扩展配置 JSON';
COMMENT ON COLUMN "knowledge_base_metadata"."status" IS '知识库状态：active、deleted 或 missing';
COMMENT ON COLUMN "knowledge_base_metadata"."created_by" IS '创建人';
COMMENT ON COLUMN "knowledge_base_metadata"."updated_by" IS '最后更新人';
COMMENT ON COLUMN "knowledge_base_metadata"."created_at" IS '创建时间';
COMMENT ON COLUMN "knowledge_base_metadata"."updated_at" IS '最后更新时间';

COMMENT ON TABLE "knowledge_base_metrics" IS '知识库与文档每日运营指标表';
COMMENT ON COLUMN "knowledge_base_metrics"."id" IS '指标记录主键 ID';
COMMENT ON COLUMN "knowledge_base_metrics"."metric_date" IS '统计日期';
COMMENT ON COLUMN "knowledge_base_metrics"."target_type" IS '统计对象类型：dataset 或 document';
COMMENT ON COLUMN "knowledge_base_metrics"."target_id" IS '统计对象 ID';
COMMENT ON COLUMN "knowledge_base_metrics"."target_name" IS '统计对象名称快照';
COMMENT ON COLUMN "knowledge_base_metrics"."citation_count" IS '被引用次数';
COMMENT ON COLUMN "knowledge_base_metrics"."search_count" IS '被搜索或召回次数';
COMMENT ON COLUMN "knowledge_base_metrics"."created_at" IS '创建时间';
COMMENT ON COLUMN "knowledge_base_metrics"."updated_at" IS '最后更新时间';

COMMENT ON TABLE "ai_agent_quota_policies" IS '用户、角色和系统 Token 额度策略表';
COMMENT ON COLUMN "ai_agent_quota_policies"."id" IS '额度策略主键 ID';
COMMENT ON COLUMN "ai_agent_quota_policies"."scope_type" IS '策略范围：user、role 或 system';
COMMENT ON COLUMN "ai_agent_quota_policies"."scope_id" IS '用户 ID 或角色 ID';
COMMENT ON COLUMN "ai_agent_quota_policies"."period" IS '额度周期';
COMMENT ON COLUMN "ai_agent_quota_policies"."limit_tokens" IS 'Token 上限，为空表示不限额';
COMMENT ON COLUMN "ai_agent_quota_policies"."enabled" IS '是否启用策略';
COMMENT ON COLUMN "ai_agent_quota_policies"."action_on_exceed" IS '超额动作';
COMMENT ON COLUMN "ai_agent_quota_policies"."created_at" IS '创建时间';
COMMENT ON COLUMN "ai_agent_quota_policies"."updated_at" IS '最后更新时间';

COMMENT ON TABLE "user_notification_configs" IS '用户个人通知渠道配置表';
COMMENT ON COLUMN "user_notification_configs"."id" IS '通知配置主键 ID';
COMMENT ON COLUMN "user_notification_configs"."user_id" IS '用户 ID';
COMMENT ON COLUMN "user_notification_configs"."channel_type" IS '通知渠道类型';
COMMENT ON COLUMN "user_notification_configs"."config_json" IS '通知渠道参数 JSON 文本';
COMMENT ON COLUMN "user_notification_configs"."created_at" IS '创建时间';
COMMENT ON COLUMN "user_notification_configs"."updated_at" IS '最后更新时间';

COMMENT ON TABLE "ai_agent_scenario_instances" IS '场景模板交付实例表';
COMMENT ON COLUMN "ai_agent_scenario_instances"."id" IS '交付实例唯一 ID';
COMMENT ON COLUMN "ai_agent_scenario_instances"."template_id" IS '场景模板 ID';
COMMENT ON COLUMN "ai_agent_scenario_instances"."template_name" IS '场景模板名称快照';
COMMENT ON COLUMN "ai_agent_scenario_instances"."agent_id" IS '交付后关联的智能体 ID';
COMMENT ON COLUMN "ai_agent_scenario_instances"."agent_name" IS '智能体标识快照';
COMMENT ON COLUMN "ai_agent_scenario_instances"."display_name" IS '交付实例显示名称';
COMMENT ON COLUMN "ai_agent_scenario_instances"."owner" IS '业务负责人或交付负责人';
COMMENT ON COLUMN "ai_agent_scenario_instances"."status" IS '交付状态';
COMMENT ON COLUMN "ai_agent_scenario_instances"."resource_bindings" IS '资源绑定快照 JSON';
COMMENT ON COLUMN "ai_agent_scenario_instances"."missing_resources" IS '缺失资源清单 JSON';
COMMENT ON COLUMN "ai_agent_scenario_instances"."deliverables" IS '本次交付物清单 JSON';
COMMENT ON COLUMN "ai_agent_scenario_instances"."acceptance_criteria" IS '验收标准快照 JSON';
COMMENT ON COLUMN "ai_agent_scenario_instances"."next_steps" IS '后续动作 JSON';
COMMENT ON COLUMN "ai_agent_scenario_instances"."created_by" IS '创建人';
COMMENT ON COLUMN "ai_agent_scenario_instances"."updated_by" IS '最后更新人';
COMMENT ON COLUMN "ai_agent_scenario_instances"."created_at" IS '创建时间';
COMMENT ON COLUMN "ai_agent_scenario_instances"."updated_at" IS '最后更新时间';

COMMENT ON TABLE "ai_agent_scenario_install_runs" IS '场景模板安装运行记录表';
COMMENT ON COLUMN "ai_agent_scenario_install_runs"."id" IS '安装运行记录唯一 ID';
COMMENT ON COLUMN "ai_agent_scenario_install_runs"."instance_id" IS '交付实例 ID';
COMMENT ON COLUMN "ai_agent_scenario_install_runs"."template_id" IS '场景模板 ID';
COMMENT ON COLUMN "ai_agent_scenario_install_runs"."agent_id" IS '关联智能体 ID';
COMMENT ON COLUMN "ai_agent_scenario_install_runs"."status" IS '安装状态：success、blocked 或 failed';
COMMENT ON COLUMN "ai_agent_scenario_install_runs"."precheck_result" IS '安装预检结果 JSON';
COMMENT ON COLUMN "ai_agent_scenario_install_runs"."install_result" IS '安装结果 JSON';
COMMENT ON COLUMN "ai_agent_scenario_install_runs"."error_message" IS '失败或阻断原因';
COMMENT ON COLUMN "ai_agent_scenario_install_runs"."created_by" IS '执行人';
COMMENT ON COLUMN "ai_agent_scenario_install_runs"."created_at" IS '运行创建时间';
